-- KISS-03A: SNMP poll recipes are management configuration. Samples remain in ClickHouse.
CREATE TABLE IF NOT EXISTS snmp_collection_recipes (
  id                      CHAR(26)     NOT NULL,
  device_id               CHAR(26)     NOT NULL,
  entity_kind             VARCHAR(48)  NOT NULL,
  entity_id               CHAR(26)     NOT NULL DEFAULT '',
  module_name             VARCHAR(96)  NOT NULL,
  metric                  VARCHAR(160) NOT NULL,
  value_kind              VARCHAR(16)  NOT NULL,
  oid                     VARCHAR(512) NOT NULL,
  numeric_oid             VARCHAR(512) NOT NULL,
  oid_index               VARCHAR(96)  NOT NULL DEFAULT '',
  mib                     VARCHAR(128) NOT NULL DEFAULT '',
  context_name            VARCHAR(96)  NOT NULL DEFAULT '',
  divisor                 DOUBLE       NULL,
  multiplier              DOUBLE       NULL,
  sample_interval_seconds INT UNSIGNED NOT NULL DEFAULT 60,
  labels_json             JSON         NOT NULL,
  options_json            JSON         NOT NULL,
  enabled                 TINYINT(1)    NOT NULL DEFAULT 1,
  discovered_at           DATETIME(3)  NOT NULL,
  last_polled_at          DATETIME(3)  NULL,
  last_error              VARCHAR(2048) NOT NULL DEFAULT '',
  created_at              DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at              DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_snmp_recipe (device_id,module_name,entity_kind,entity_id,metric,oid_index,context_name),
  KEY idx_snmp_recipe_due (enabled,last_polled_at,sample_interval_seconds),
  CONSTRAINT fk_snmp_recipe_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
