-- Global Flow storage lifecycle. There is one installation-wide policy stream:
-- no tenant key and no configuration-file retention authority.
CREATE TABLE IF NOT EXISTS flow_retention_policy_revisions (
  id                            CHAR(26)        NOT NULL,
  policy_version                BIGINT UNSIGNED NOT NULL,
  status                        VARCHAR(16)     NOT NULL DEFAULT 'draft',
  bootstrap_from                DATE            NOT NULL,
  raw_retention_seconds         BIGINT UNSIGNED NOT NULL,
  archive_resolution_seconds    INT UNSIGNED    NOT NULL DEFAULT 3600,
  archive_retention_seconds     BIGINT UNSIGNED NOT NULL DEFAULT 0,
  late_arrival_seconds          INT UNSIGNED    NOT NULL,
  delete_grace_seconds          INT UNSIGNED    NOT NULL,
  max_partitions_per_run        INT UNSIGNED    NOT NULL DEFAULT 7,
  raw_delete_enabled            TINYINT(1)      NOT NULL DEFAULT 0,
  archive_delete_enabled        TINYINT(1)      NOT NULL DEFAULT 0,
  require_backup_before_delete  TINYINT(1)      NOT NULL DEFAULT 1,
  active_singleton              TINYINT GENERATED ALWAYS AS (IF(status = 'published', 1, NULL)) STORED,
  row_version                   BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by                    CHAR(26)        NULL,
  published_by                  CHAR(26)        NULL,
  retired_by                    CHAR(26)        NULL,
  created_at                    DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  published_at                  DATETIME(3)     NULL,
  retired_at                    DATETIME(3)     NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_retention_policy_version (policy_version),
  UNIQUE KEY uq_flow_retention_active (active_singleton),
  CONSTRAINT fk_flow_retention_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_flow_retention_published_by FOREIGN KEY (published_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_flow_retention_retired_by FOREIGN KEY (retired_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (status IN ('draft', 'published', 'retired')),
  CHECK (policy_version BETWEEN 1 AND 4294967295),
  CHECK (raw_retention_seconds BETWEEN 86400 AND 315576000),
  CHECK (archive_resolution_seconds = 3600),
  CHECK (archive_retention_seconds = 0 OR archive_retention_seconds > raw_retention_seconds),
  CHECK (late_arrival_seconds <= 604800),
  CHECK (delete_grace_seconds BETWEEN 3600 AND 2592000),
  CHECK (max_partitions_per_run BETWEEN 1 AND 366),
  CHECK (raw_delete_enabled IN (0, 1)),
  CHECK (archive_delete_enabled IN (0, 1)),
  CHECK (require_backup_before_delete IN (0, 1)),
  CHECK ((status = 'draft' AND published_at IS NULL AND retired_at IS NULL)
      OR (status = 'published' AND published_at IS NOT NULL AND retired_at IS NULL)
      OR (status = 'retired' AND published_at IS NOT NULL AND retired_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Archive/reconciliation is day-scoped because flow_records is partitioned by
-- toYYYYMMDD(event_time). The generation encodes policy_version:repair_attempt.
CREATE TABLE IF NOT EXISTS flow_retention_partition_states (
  source_date                       DATE            NOT NULL,
  policy_id                         CHAR(26)        NOT NULL,
  policy_version                    BIGINT UNSIGNED NOT NULL,
  state                             VARCHAR(24)     NOT NULL,
  generation                        BIGINT UNSIGNED NOT NULL,
  repair_attempt                    INT UNSIGNED    NOT NULL DEFAULT 1,
  source_record_count               BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_raw_bytes                  BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_raw_packets                BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_estimated_bytes            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_estimated_packets          BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_estimated_valid_records    BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_record_count              BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_raw_bytes                 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_raw_packets               BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_estimated_bytes           BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_estimated_packets         BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_estimated_valid_records   BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_job_id                    CHAR(26)        NULL,
  delete_job_id                     CHAR(26)        NULL,
  archived_at                       DATETIME(3)     NULL,
  reconciled_at                     DATETIME(3)     NULL,
  delete_eligible_at                DATETIME(3)     NULL,
  raw_deleted_at                    DATETIME(3)     NULL,
  last_error_code                   VARCHAR(64)     NULL,
  last_error_detail                 TEXT            NULL,
  row_version                       BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at                        DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at                        DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (source_date),
  KEY idx_flow_retention_partition_state (state, source_date),
  CONSTRAINT fk_flow_retention_partition_policy FOREIGN KEY (policy_id) REFERENCES flow_retention_policy_revisions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_flow_retention_archive_job FOREIGN KEY (archive_job_id) REFERENCES operation_jobs(id) ON DELETE SET NULL,
  CONSTRAINT fk_flow_retention_delete_job FOREIGN KEY (delete_job_id) REFERENCES operation_jobs(id) ON DELETE SET NULL,
  CHECK (state IN ('sealed', 'archive_written', 'reconciled', 'delete_eligible', 'raw_deleted', 'failed')),
  CHECK (repair_attempt >= 1),
  CHECK (generation = (policy_version << 32) + repair_attempt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Durable high-water marks are Kafka next offsets. A scanner snapshots the
-- broker's stable committed offset, then advances reconciled_next_offset only
-- across a contiguous receipt/fact window whose count and counters agree.
CREATE TABLE IF NOT EXISTS flow_reconciliation_watermarks (
  source_stream_id          VARCHAR(128)    NOT NULL,
  kafka_topic               VARCHAR(249)    NOT NULL,
  consumer_group            VARCHAR(249)    NOT NULL,
  kafka_partition           INT UNSIGNED    NOT NULL,
  bootstrap_offset          BIGINT UNSIGNED NOT NULL,
  committed_next_offset     BIGINT UNSIGNED NOT NULL,
  reconciled_next_offset    BIGINT UNSIGNED NOT NULL,
  status                    VARCHAR(16)     NOT NULL DEFAULT 'initializing',
  mismatch_count            BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_error_code           VARCHAR(64)     NULL,
  last_error_detail         TEXT            NULL,
  committed_snapshot_at     DATETIME(3)     NULL,
  last_verified_at          DATETIME(3)     NULL,
  row_version               BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at                DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at                DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (source_stream_id, kafka_partition),
  UNIQUE KEY uq_flow_reconciliation_group_partition (kafka_topic, consumer_group, kafka_partition),
  CHECK (status IN ('initializing', 'healthy', 'mismatch', 'blocked')),
  CHECK (bootstrap_offset <= reconciled_next_offset),
  CHECK (reconciled_next_offset <= committed_next_offset)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Destructive jobs may reference only a verified, non-revoked backup whose
-- covered interval contains the raw day or archive month being removed.
CREATE TABLE IF NOT EXISTS flow_backup_restore_evidence (
  id                    CHAR(26)        NOT NULL,
  storage_kind          VARCHAR(16)     NOT NULL,
  covered_from          DATE            NOT NULL,
  covered_through       DATE            NOT NULL,
  backup_ref            VARCHAR(512)    NOT NULL,
  checksum_sha256       CHAR(64)        NOT NULL,
  status                VARCHAR(16)     NOT NULL DEFAULT 'verified',
  verified_by           CHAR(26)        NULL,
  verified_at           DATETIME(3)     NOT NULL,
  restore_tested_at     DATETIME(3)     NOT NULL,
  revoked_by            CHAR(26)        NULL,
  revoked_at            DATETIME(3)     NULL,
  created_at            DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_backup_ref (backup_ref),
  KEY idx_flow_backup_coverage (storage_kind, status, covered_from, covered_through),
  CONSTRAINT fk_flow_backup_verified_by FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_flow_backup_revoked_by FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (storage_kind IN ('raw', 'archive', 'all')),
  CHECK (status IN ('verified', 'revoked')),
  CHECK (covered_from < covered_through),
  CHECK ((status = 'verified' AND revoked_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Immutable audit of every physical partition deletion. coverage_json freezes
-- the per-partition committed/reconciled next offsets used by the guard.
CREATE TABLE IF NOT EXISTS flow_deletion_receipts (
  id                         CHAR(26)        NOT NULL,
  storage_kind               VARCHAR(16)     NOT NULL,
  partition_granularity      VARCHAR(8)      NOT NULL,
  partition_start            DATE            NOT NULL,
  partition_end              DATE            NOT NULL,
  policy_id                  CHAR(26)        NOT NULL,
  policy_version             BIGINT UNSIGNED NOT NULL,
  generation                 BIGINT UNSIGNED NOT NULL,
  operation_job_id           CHAR(26)        NOT NULL,
  backup_evidence_id         CHAR(26)        NULL,
  kafka_coverage_json        JSON            NOT NULL,
  source_record_count        BIGINT UNSIGNED NOT NULL,
  source_raw_bytes           BIGINT UNSIGNED NOT NULL,
  source_raw_packets         BIGINT UNSIGNED NOT NULL,
  source_estimated_bytes     BIGINT UNSIGNED NOT NULL,
  source_estimated_packets   BIGINT UNSIGNED NOT NULL,
  ch_query_id                VARCHAR(128)    NOT NULL,
  status                     VARCHAR(16)     NOT NULL,
  requested_by               CHAR(26)        NULL,
  requested_at               DATETIME(3)     NOT NULL,
  completed_at               DATETIME(3)     NULL,
  error_code                 VARCHAR(64)     NULL,
  error_detail               TEXT            NULL,
  created_at                 DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_deletion_partition (storage_kind, partition_start, generation),
  KEY idx_flow_deletion_status (status, requested_at),
  CONSTRAINT fk_flow_deletion_policy FOREIGN KEY (policy_id) REFERENCES flow_retention_policy_revisions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_flow_deletion_job FOREIGN KEY (operation_job_id) REFERENCES operation_jobs(id) ON DELETE RESTRICT,
  CONSTRAINT fk_flow_deletion_backup FOREIGN KEY (backup_evidence_id) REFERENCES flow_backup_restore_evidence(id) ON DELETE RESTRICT,
  CONSTRAINT fk_flow_deletion_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
  CHECK (storage_kind IN ('raw', 'archive')),
  CHECK (partition_granularity IN ('day', 'month')),
  CHECK ((storage_kind = 'raw' AND partition_granularity = 'day' AND partition_end = partition_start + INTERVAL 1 DAY)
      OR (storage_kind = 'archive' AND partition_granularity = 'month' AND DAY(partition_start) = 1 AND partition_end = partition_start + INTERVAL 1 MONTH)),
  CHECK (status IN ('requested', 'succeeded', 'failed')),
  CHECK ((status = 'requested' AND completed_at IS NULL)
      OR (status IN ('succeeded', 'failed') AND completed_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
