-- FLOW-03H v2: independently versioned enrichment artifacts are composed by a
-- signed, worker-scoped deployment manifest. Device bindings remain placement
-- recommendations; the deployment rows are the authorization source of truth.

CREATE TABLE IF NOT EXISTS flow_artifacts (
  id               CHAR(26)        NOT NULL,
  kind             VARCHAR(32)     NOT NULL,
  scope_id         VARCHAR(128)    NOT NULL,
  version          BIGINT UNSIGNED NOT NULL,
  format           VARCHAR(16)     NOT NULL,
  format_version   SMALLINT UNSIGNED NOT NULL,
  checksum         CHAR(71)        NOT NULL,
  size_bytes       BIGINT UNSIGNED NOT NULL,
  object_ref       VARCHAR(512)    NOT NULL,
  source_revision  VARCHAR(128)    NOT NULL,
  effective_from   DATETIME(3)     NOT NULL,
  created_by       CHAR(26)        NULL,
  created_at       DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_artifact_version (kind, scope_id, version),
  UNIQUE KEY uq_flow_artifact_checksum (kind, scope_id, checksum),
  KEY idx_flow_artifact_effective (kind, scope_id, effective_from, version),
  KEY idx_flow_artifact_source (kind, scope_id, source_revision, version),
  CONSTRAINT fk_flow_artifact_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_flow_artifact_kind CHECK (kind IN ('address_catalog','device_boundary','classification_policy')),
  CONSTRAINT chk_flow_artifact_format CHECK (format IN ('wads','json')),
  CONSTRAINT chk_flow_artifact_version CHECK (version > 0 AND format_version > 0 AND size_bytes > 0),
  CONSTRAINT chk_flow_artifact_checksum CHECK (checksum REGEXP '^sha256:[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flow_worker_deployments (
  id                   CHAR(26)        NOT NULL,
  worker_id            CHAR(26)        NOT NULL,
  generation           BIGINT UNSIGNED NOT NULL,
  effective_from       DATETIME(3)     NOT NULL,
  manifest_checksum    CHAR(71)        NOT NULL,
  manifest_object_ref  VARCHAR(512)    NOT NULL,
  signature_algorithm  VARCHAR(16)     NOT NULL,
  signing_key_id       VARCHAR(64)     NOT NULL,
  signature            VARBINARY(64)   NOT NULL,
  signed_at            DATETIME(3)     NOT NULL,
  state                VARCHAR(16)     NOT NULL DEFAULT 'desired',
  operation_job_id     CHAR(26)        NULL,
  row_version          BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by           CHAR(26)        NULL,
  created_at           DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_worker_deployment_generation (worker_id, generation),
  UNIQUE KEY uq_flow_worker_deployment_effective (worker_id, effective_from),
  KEY idx_flow_worker_deployment_desired (worker_id, state, generation),
  KEY idx_flow_worker_deployment_job (operation_job_id),
  CONSTRAINT fk_flow_worker_deployment_worker FOREIGN KEY (worker_id) REFERENCES agents(id) ON DELETE RESTRICT,
  CONSTRAINT fk_flow_worker_deployment_job FOREIGN KEY (operation_job_id) REFERENCES operation_jobs(id) ON DELETE SET NULL,
  CONSTRAINT fk_flow_worker_deployment_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_flow_worker_deployment_generation CHECK (generation > 0),
  CONSTRAINT chk_flow_worker_deployment_checksum CHECK (manifest_checksum REGEXP '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT chk_flow_worker_deployment_signature CHECK (signature_algorithm = 'ed25519' AND OCTET_LENGTH(signature) = 64),
  CONSTRAINT chk_flow_worker_deployment_state CHECK (state IN ('desired','superseded','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flow_worker_deployment_artifacts (
  deployment_id  CHAR(26)     NOT NULL,
  artifact_id    CHAR(26)     NOT NULL,
  kind           VARCHAR(32)  NOT NULL,
  scope_id       VARCHAR(128) NOT NULL,
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (deployment_id, kind, scope_id),
  UNIQUE KEY uq_flow_worker_deployment_artifact (deployment_id, artifact_id),
  KEY idx_flow_worker_deployment_artifact_reverse (artifact_id, deployment_id),
  CONSTRAINT fk_flow_worker_deployment_artifact_deployment FOREIGN KEY (deployment_id) REFERENCES flow_worker_deployments(id) ON DELETE CASCADE,
  CONSTRAINT fk_flow_worker_deployment_artifact_object FOREIGN KEY (artifact_id) REFERENCES flow_artifacts(id) ON DELETE RESTRICT,
  CONSTRAINT chk_flow_worker_deployment_artifact_kind CHECK (kind IN ('address_catalog','device_boundary','classification_policy'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flow_worker_deployment_acks (
  deployment_id       CHAR(26)        NOT NULL,
  worker_id           CHAR(26)        NOT NULL,
  generation          BIGINT UNSIGNED NOT NULL,
  manifest_checksum   CHAR(71)        NOT NULL,
  boot_id             VARCHAR(128)    NOT NULL,
  software_version    VARCHAR(64)     NOT NULL,
  state               VARCHAR(16)     NOT NULL,
  attempted_at        DATETIME(3)     NOT NULL,
  downloaded_at       DATETIME(3)     NULL,
  verified_at         DATETIME(3)     NULL,
  installed_at        DATETIME(3)     NULL,
  failure_stage       VARCHAR(16)     NULL,
  error_code          VARCHAR(64)     NULL,
  error_message       VARCHAR(512)    NULL,
  installed_artifacts JSON            NULL,
  row_version         BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (deployment_id, worker_id),
  KEY idx_flow_worker_deployment_ack_worker (worker_id, attempted_at),
  KEY idx_flow_worker_deployment_ack_state (deployment_id, state, attempted_at),
  CONSTRAINT fk_flow_worker_deployment_ack_deployment FOREIGN KEY (deployment_id) REFERENCES flow_worker_deployments(id) ON DELETE CASCADE,
  CONSTRAINT fk_flow_worker_deployment_ack_worker FOREIGN KEY (worker_id) REFERENCES agents(id) ON DELETE CASCADE,
  CONSTRAINT chk_flow_worker_deployment_ack_generation CHECK (generation > 0),
  CONSTRAINT chk_flow_worker_deployment_ack_checksum CHECK (manifest_checksum REGEXP '^sha256:[0-9a-f]{64}$'),
  CONSTRAINT chk_flow_worker_deployment_ack_state CHECK (state IN ('downloaded','verified','installed','failed')),
  CONSTRAINT chk_flow_worker_deployment_ack_downloaded CHECK (state NOT IN ('downloaded','verified','installed') OR downloaded_at IS NOT NULL),
  CONSTRAINT chk_flow_worker_deployment_ack_verified CHECK (state NOT IN ('verified','installed') OR verified_at IS NOT NULL),
  CONSTRAINT chk_flow_worker_deployment_ack_installed CHECK (state <> 'installed' OR installed_at IS NOT NULL),
  CONSTRAINT chk_flow_worker_deployment_ack_failed CHECK ((state = 'failed') = (error_code IS NOT NULL AND failure_stage IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
