// SPDX-FileCopyrightText: 2022 Free Mobile
// SPDX-License-Identifier: AGPL-3.0-only
//
// Adapted from Akvorado common/pb/rawflow.proto for Watchdog. The additional
// fields bind an undecoded datagram to its collector configuration without
// putting tenant or dimension lookups on the UDP receive path.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/flowstream/flowpb/rawflow.proto

package flowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawFlow_Decoder int32

const (
	RawFlow_DECODER_UNSPECIFIED RawFlow_Decoder = 0
	RawFlow_DECODER_NETFLOW     RawFlow_Decoder = 1
	RawFlow_DECODER_SFLOW       RawFlow_Decoder = 2
	RawFlow_DECODER_GOB         RawFlow_Decoder = 3
)

// Enum value maps for RawFlow_Decoder.
var (
	RawFlow_Decoder_name = map[int32]string{
		0: "DECODER_UNSPECIFIED",
		1: "DECODER_NETFLOW",
		2: "DECODER_SFLOW",
		3: "DECODER_GOB",
	}
	RawFlow_Decoder_value = map[string]int32{
		"DECODER_UNSPECIFIED": 0,
		"DECODER_NETFLOW":     1,
		"DECODER_SFLOW":       2,
		"DECODER_GOB":         3,
	}
)

func (x RawFlow_Decoder) Enum() *RawFlow_Decoder {
	p := new(RawFlow_Decoder)
	*p = x
	return p
}

func (x RawFlow_Decoder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RawFlow_Decoder) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_flowstream_flowpb_rawflow_proto_enumTypes[0].Descriptor()
}

func (RawFlow_Decoder) Type() protoreflect.EnumType {
	return &file_internal_flowstream_flowpb_rawflow_proto_enumTypes[0]
}

func (x RawFlow_Decoder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RawFlow_Decoder.Descriptor instead.
func (RawFlow_Decoder) EnumDescriptor() ([]byte, []int) {
	return file_internal_flowstream_flowpb_rawflow_proto_rawDescGZIP(), []int{0, 0}
}

type RawFlow_TimestampSource int32

const (
	RawFlow_TS_INPUT                  RawFlow_TimestampSource = 0
	RawFlow_TS_NETFLOW_PACKET         RawFlow_TimestampSource = 1
	RawFlow_TS_NETFLOW_FIRST_SWITCHED RawFlow_TimestampSource = 2
)

// Enum value maps for RawFlow_TimestampSource.
var (
	RawFlow_TimestampSource_name = map[int32]string{
		0: "TS_INPUT",
		1: "TS_NETFLOW_PACKET",
		2: "TS_NETFLOW_FIRST_SWITCHED",
	}
	RawFlow_TimestampSource_value = map[string]int32{
		"TS_INPUT":                  0,
		"TS_NETFLOW_PACKET":         1,
		"TS_NETFLOW_FIRST_SWITCHED": 2,
	}
)

func (x RawFlow_TimestampSource) Enum() *RawFlow_TimestampSource {
	p := new(RawFlow_TimestampSource)
	*p = x
	return p
}

func (x RawFlow_TimestampSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RawFlow_TimestampSource) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_flowstream_flowpb_rawflow_proto_enumTypes[1].Descriptor()
}

func (RawFlow_TimestampSource) Type() protoreflect.EnumType {
	return &file_internal_flowstream_flowpb_rawflow_proto_enumTypes[1]
}

func (x RawFlow_TimestampSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RawFlow_TimestampSource.Descriptor instead.
func (RawFlow_TimestampSource) EnumDescriptor() ([]byte, []int) {
	return file_internal_flowstream_flowpb_rawflow_proto_rawDescGZIP(), []int{0, 1}
}

type RawFlow_DecapsulationProtocol int32

const (
	RawFlow_DECAP_NONE  RawFlow_DecapsulationProtocol = 0
	RawFlow_DECAP_IPIP  RawFlow_DecapsulationProtocol = 1
	RawFlow_DECAP_GRE   RawFlow_DecapsulationProtocol = 2
	RawFlow_DECAP_VXLAN RawFlow_DecapsulationProtocol = 3
	RawFlow_DECAP_SRV6  RawFlow_DecapsulationProtocol = 4
)

// Enum value maps for RawFlow_DecapsulationProtocol.
var (
	RawFlow_DecapsulationProtocol_name = map[int32]string{
		0: "DECAP_NONE",
		1: "DECAP_IPIP",
		2: "DECAP_GRE",
		3: "DECAP_VXLAN",
		4: "DECAP_SRV6",
	}
	RawFlow_DecapsulationProtocol_value = map[string]int32{
		"DECAP_NONE":  0,
		"DECAP_IPIP":  1,
		"DECAP_GRE":   2,
		"DECAP_VXLAN": 3,
		"DECAP_SRV6":  4,
	}
)

func (x RawFlow_DecapsulationProtocol) Enum() *RawFlow_DecapsulationProtocol {
	p := new(RawFlow_DecapsulationProtocol)
	*p = x
	return p
}

func (x RawFlow_DecapsulationProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RawFlow_DecapsulationProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_flowstream_flowpb_rawflow_proto_enumTypes[2].Descriptor()
}

func (RawFlow_DecapsulationProtocol) Type() protoreflect.EnumType {
	return &file_internal_flowstream_flowpb_rawflow_proto_enumTypes[2]
}

func (x RawFlow_DecapsulationProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RawFlow_DecapsulationProtocol.Descriptor instead.
func (RawFlow_DecapsulationProtocol) EnumDescriptor() ([]byte, []int) {
	return file_internal_flowstream_flowpb_rawflow_proto_rawDescGZIP(), []int{0, 2}
}

type RawFlow struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	TimeReceived          uint64                        `protobuf:"varint,1,opt,name=time_received,json=timeReceived,proto3" json:"time_received,omitempty"`
	Payload               []byte                        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SourceAddress         []byte                        `protobuf:"bytes,3,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	UseSourceAddress      bool                          `protobuf:"varint,4,opt,name=use_source_address,json=useSourceAddress,proto3" json:"use_source_address,omitempty"`
	Decoder               RawFlow_Decoder               `protobuf:"varint,5,opt,name=decoder,proto3,enum=watchdog.flow.raw.v1.RawFlow_Decoder" json:"decoder,omitempty"`
	TimestampSource       RawFlow_TimestampSource       `protobuf:"varint,6,opt,name=timestamp_source,json=timestampSource,proto3,enum=watchdog.flow.raw.v1.RawFlow_TimestampSource" json:"timestamp_source,omitempty"`
	DecapsulationProtocol RawFlow_DecapsulationProtocol `protobuf:"varint,7,opt,name=decapsulation_protocol,json=decapsulationProtocol,proto3,enum=watchdog.flow.raw.v1.RawFlow_DecapsulationProtocol" json:"decapsulation_protocol,omitempty"`
	RateLimit             uint64                        `protobuf:"varint,8,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	CollectorId           string                        `protobuf:"bytes,9,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ListenerId            string                        `protobuf:"bytes,10,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	SourcePort            uint32                        `protobuf:"varint,11,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	RegistryVersion       uint64                        `protobuf:"varint,12,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RawFlow) Reset() {
	*x = RawFlow{}
	mi := &file_internal_flowstream_flowpb_rawflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawFlow) ProtoMessage() {}

func (x *RawFlow) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowstream_flowpb_rawflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawFlow.ProtoReflect.Descriptor instead.
func (*RawFlow) Descriptor() ([]byte, []int) {
	return file_internal_flowstream_flowpb_rawflow_proto_rawDescGZIP(), []int{0}
}

func (x *RawFlow) GetTimeReceived() uint64 {
	if x != nil {
		return x.TimeReceived
	}
	return 0
}

func (x *RawFlow) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RawFlow) GetSourceAddress() []byte {
	if x != nil {
		return x.SourceAddress
	}
	return nil
}

func (x *RawFlow) GetUseSourceAddress() bool {
	if x != nil {
		return x.UseSourceAddress
	}
	return false
}

func (x *RawFlow) GetDecoder() RawFlow_Decoder {
	if x != nil {
		return x.Decoder
	}
	return RawFlow_DECODER_UNSPECIFIED
}

func (x *RawFlow) GetTimestampSource() RawFlow_TimestampSource {
	if x != nil {
		return x.TimestampSource
	}
	return RawFlow_TS_INPUT
}

func (x *RawFlow) GetDecapsulationProtocol() RawFlow_DecapsulationProtocol {
	if x != nil {
		return x.DecapsulationProtocol
	}
	return RawFlow_DECAP_NONE
}

func (x *RawFlow) GetRateLimit() uint64 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

func (x *RawFlow) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *RawFlow) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *RawFlow) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *RawFlow) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

var File_internal_flowstream_flowpb_rawflow_proto protoreflect.FileDescriptor

const file_internal_flowstream_flowpb_rawflow_proto_rawDesc = "" +
	"\n" +
	"(internal/flowstream/flowpb/rawflow.proto\x12\x14watchdog.flow.raw.v1\"\xf0\x06\n" +
	"\aRawFlow\x12#\n" +
	"\rtime_received\x18\x01 \x01(\x04R\ftimeReceived\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12%\n" +
	"\x0esource_address\x18\x03 \x01(\fR\rsourceAddress\x12,\n" +
	"\x12use_source_address\x18\x04 \x01(\bR\x10useSourceAddress\x12?\n" +
	"\adecoder\x18\x05 \x01(\x0e2%.watchdog.flow.raw.v1.RawFlow.DecoderR\adecoder\x12X\n" +
	"\x10timestamp_source\x18\x06 \x01(\x0e2-.watchdog.flow.raw.v1.RawFlow.TimestampSourceR\x0ftimestampSource\x12j\n" +
	"\x16decapsulation_protocol\x18\a \x01(\x0e23.watchdog.flow.raw.v1.RawFlow.DecapsulationProtocolR\x15decapsulationProtocol\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\b \x01(\x04R\trateLimit\x12!\n" +
	"\fcollector_id\x18\t \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vlistener_id\x18\n" +
	" \x01(\tR\n" +
	"listenerId\x12\x1f\n" +
	"\vsource_port\x18\v \x01(\rR\n" +
	"sourcePort\x12)\n" +
	"\x10registry_version\x18\f \x01(\x04R\x0fregistryVersion\"[\n" +
	"\aDecoder\x12\x17\n" +
	"\x13DECODER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDECODER_NETFLOW\x10\x01\x12\x11\n" +
	"\rDECODER_SFLOW\x10\x02\x12\x0f\n" +
	"\vDECODER_GOB\x10\x03\"U\n" +
	"\x0fTimestampSource\x12\f\n" +
	"\bTS_INPUT\x10\x00\x12\x15\n" +
	"\x11TS_NETFLOW_PACKET\x10\x01\x12\x1d\n" +
	"\x19TS_NETFLOW_FIRST_SWITCHED\x10\x02\"g\n" +
	"\x15DecapsulationProtocol\x12\x0e\n" +
	"\n" +
	"DECAP_NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"DECAP_IPIP\x10\x01\x12\r\n" +
	"\tDECAP_GRE\x10\x02\x12\x0f\n" +
	"\vDECAP_VXLAN\x10\x03\x12\x0e\n" +
	"\n" +
	"DECAP_SRV6\x10\x04B;Z9github.com/cloudcache/watchdog/internal/flowstream/flowpbb\x06proto3"

var (
	file_internal_flowstream_flowpb_rawflow_proto_rawDescOnce sync.Once
	file_internal_flowstream_flowpb_rawflow_proto_rawDescData []byte
)

func file_internal_flowstream_flowpb_rawflow_proto_rawDescGZIP() []byte {
	file_internal_flowstream_flowpb_rawflow_proto_rawDescOnce.Do(func() {
		file_internal_flowstream_flowpb_rawflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_flowstream_flowpb_rawflow_proto_rawDesc), len(file_internal_flowstream_flowpb_rawflow_proto_rawDesc)))
	})
	return file_internal_flowstream_flowpb_rawflow_proto_rawDescData
}

var file_internal_flowstream_flowpb_rawflow_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_flowstream_flowpb_rawflow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_flowstream_flowpb_rawflow_proto_goTypes = []any{
	(RawFlow_Decoder)(0),               // 0: watchdog.flow.raw.v1.RawFlow.Decoder
	(RawFlow_TimestampSource)(0),       // 1: watchdog.flow.raw.v1.RawFlow.TimestampSource
	(RawFlow_DecapsulationProtocol)(0), // 2: watchdog.flow.raw.v1.RawFlow.DecapsulationProtocol
	(*RawFlow)(nil),                    // 3: watchdog.flow.raw.v1.RawFlow
}
var file_internal_flowstream_flowpb_rawflow_proto_depIdxs = []int32{
	0, // 0: watchdog.flow.raw.v1.RawFlow.decoder:type_name -> watchdog.flow.raw.v1.RawFlow.Decoder
	1, // 1: watchdog.flow.raw.v1.RawFlow.timestamp_source:type_name -> watchdog.flow.raw.v1.RawFlow.TimestampSource
	2, // 2: watchdog.flow.raw.v1.RawFlow.decapsulation_protocol:type_name -> watchdog.flow.raw.v1.RawFlow.DecapsulationProtocol
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_flowstream_flowpb_rawflow_proto_init() }
func file_internal_flowstream_flowpb_rawflow_proto_init() {
	if File_internal_flowstream_flowpb_rawflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_flowstream_flowpb_rawflow_proto_rawDesc), len(file_internal_flowstream_flowpb_rawflow_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_flowstream_flowpb_rawflow_proto_goTypes,
		DependencyIndexes: file_internal_flowstream_flowpb_rawflow_proto_depIdxs,
		EnumInfos:         file_internal_flowstream_flowpb_rawflow_proto_enumTypes,
		MessageInfos:      file_internal_flowstream_flowpb_rawflow_proto_msgTypes,
	}.Build()
	File_internal_flowstream_flowpb_rawflow_proto = out.File
	file_internal_flowstream_flowpb_rawflow_proto_goTypes = nil
	file_internal_flowstream_flowpb_rawflow_proto_depIdxs = nil
}
