// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/flowcollect/flowpb/normalized.proto

package flowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NormalizedRecordBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BatchSchemaVersion  uint32                 `protobuf:"varint,1,opt,name=batch_schema_version,json=batchSchemaVersion,proto3" json:"batch_schema_version,omitempty"`
	NormalizedBatchId   []byte                 `protobuf:"bytes,2,opt,name=normalized_batch_id,json=normalizedBatchId,proto3" json:"normalized_batch_id,omitempty"`
	DatagramId          []byte                 `protobuf:"bytes,3,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	VirtualShard        uint32                 `protobuf:"varint,4,opt,name=virtual_shard,json=virtualShard,proto3" json:"virtual_shard,omitempty"`
	PartitionMapVersion uint32                 `protobuf:"varint,5,opt,name=partition_map_version,json=partitionMapVersion,proto3" json:"partition_map_version,omitempty"`
	PhysicalPartition   uint32                 `protobuf:"varint,6,opt,name=physical_partition,json=physicalPartition,proto3" json:"physical_partition,omitempty"`
	ReplayGeneration    uint32                 `protobuf:"varint,7,opt,name=replay_generation,json=replayGeneration,proto3" json:"replay_generation,omitempty"`
	TenantId            string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectorId         string                 `protobuf:"bytes,9,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ExporterId          string                 `protobuf:"bytes,10,opt,name=exporter_id,json=exporterId,proto3" json:"exporter_id,omitempty"`
	RegistryVersion     uint64                 `protobuf:"varint,11,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	ReceivedAtUnixMs    int64                  `protobuf:"varint,12,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Protocol            uint32                 `protobuf:"varint,13,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp            []byte                 `protobuf:"bytes,14,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ObservationDomainId uint64                 `protobuf:"varint,15,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	Records             []*NormalizedRecord    `protobuf:"bytes,16,rep,name=records,proto3" json:"records,omitempty"`
	// sFlow datagram state. Per-sample state remains on each record.
	SubAgentId       uint32 `protobuf:"varint,32,opt,name=sub_agent_id,json=subAgentId,proto3" json:"sub_agent_id,omitempty"`
	DatagramSequence uint32 `protobuf:"varint,33,opt,name=datagram_sequence,json=datagramSequence,proto3" json:"datagram_sequence,omitempty"`
	AgentIp          []byte `protobuf:"bytes,34,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NormalizedRecordBatch) Reset() {
	*x = NormalizedRecordBatch{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedRecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedRecordBatch) ProtoMessage() {}

func (x *NormalizedRecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedRecordBatch.ProtoReflect.Descriptor instead.
func (*NormalizedRecordBatch) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedRecordBatch) GetBatchSchemaVersion() uint32 {
	if x != nil {
		return x.BatchSchemaVersion
	}
	return 0
}

func (x *NormalizedRecordBatch) GetNormalizedBatchId() []byte {
	if x != nil {
		return x.NormalizedBatchId
	}
	return nil
}

func (x *NormalizedRecordBatch) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *NormalizedRecordBatch) GetVirtualShard() uint32 {
	if x != nil {
		return x.VirtualShard
	}
	return 0
}

func (x *NormalizedRecordBatch) GetPartitionMapVersion() uint32 {
	if x != nil {
		return x.PartitionMapVersion
	}
	return 0
}

func (x *NormalizedRecordBatch) GetPhysicalPartition() uint32 {
	if x != nil {
		return x.PhysicalPartition
	}
	return 0
}

func (x *NormalizedRecordBatch) GetReplayGeneration() uint32 {
	if x != nil {
		return x.ReplayGeneration
	}
	return 0
}

func (x *NormalizedRecordBatch) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NormalizedRecordBatch) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *NormalizedRecordBatch) GetExporterId() string {
	if x != nil {
		return x.ExporterId
	}
	return ""
}

func (x *NormalizedRecordBatch) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

func (x *NormalizedRecordBatch) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *NormalizedRecordBatch) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *NormalizedRecordBatch) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *NormalizedRecordBatch) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *NormalizedRecordBatch) GetRecords() []*NormalizedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *NormalizedRecordBatch) GetSubAgentId() uint32 {
	if x != nil {
		return x.SubAgentId
	}
	return 0
}

func (x *NormalizedRecordBatch) GetDatagramSequence() uint32 {
	if x != nil {
		return x.DatagramSequence
	}
	return 0
}

func (x *NormalizedRecordBatch) GetAgentIp() []byte {
	if x != nil {
		return x.AgentIp
	}
	return nil
}

type NormalizedRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RecordIndex          uint32                 `protobuf:"varint,1,opt,name=record_index,json=recordIndex,proto3" json:"record_index,omitempty"`
	EventTimeUnixMs      int64                  `protobuf:"varint,2,opt,name=event_time_unix_ms,json=eventTimeUnixMs,proto3" json:"event_time_unix_ms,omitempty"`
	TargetId             string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DeviceId             string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ObservationIfIndex   uint32                 `protobuf:"varint,5,opt,name=observation_if_index,json=observationIfIndex,proto3" json:"observation_if_index,omitempty"`
	ObservationDirection uint32                 `protobuf:"varint,6,opt,name=observation_direction,json=observationDirection,proto3" json:"observation_direction,omitempty"`
	InIf                 uint32                 `protobuf:"varint,7,opt,name=in_if,json=inIf,proto3" json:"in_if,omitempty"`
	OutIf                uint32                 `protobuf:"varint,8,opt,name=out_if,json=outIf,proto3" json:"out_if,omitempty"`
	SrcIp                []byte                 `protobuf:"bytes,9,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp                []byte                 `protobuf:"bytes,10,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort              uint32                 `protobuf:"varint,11,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort              uint32                 `protobuf:"varint,12,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	IpProto              uint32                 `protobuf:"varint,13,opt,name=ip_proto,json=ipProto,proto3" json:"ip_proto,omitempty"`
	TcpFlags             uint32                 `protobuf:"varint,14,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	RawBytes             uint64                 `protobuf:"varint,15,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	RawPackets           uint64                 `protobuf:"varint,16,opt,name=raw_packets,json=rawPackets,proto3" json:"raw_packets,omitempty"`
	SamplingMode         uint32                 `protobuf:"varint,17,opt,name=sampling_mode,json=samplingMode,proto3" json:"sampling_mode,omitempty"`
	SamplingRate         uint64                 `protobuf:"varint,18,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	EstimatedBytes       uint64                 `protobuf:"varint,19,opt,name=estimated_bytes,json=estimatedBytes,proto3" json:"estimated_bytes,omitempty"`
	EstimatedPackets     uint64                 `protobuf:"varint,20,opt,name=estimated_packets,json=estimatedPackets,proto3" json:"estimated_packets,omitempty"`
	FlowDurationMs       uint64                 `protobuf:"varint,21,opt,name=flow_duration_ms,json=flowDurationMs,proto3" json:"flow_duration_ms,omitempty"`
	QualityFlags         uint64                 `protobuf:"varint,22,opt,name=quality_flags,json=qualityFlags,proto3" json:"quality_flags,omitempty"`
	SrcAs                uint32                 `protobuf:"varint,32,opt,name=src_as,json=srcAs,proto3" json:"src_as,omitempty"`
	DstAs                uint32                 `protobuf:"varint,33,opt,name=dst_as,json=dstAs,proto3" json:"dst_as,omitempty"`
	SourceIdType         uint32                 `protobuf:"varint,34,opt,name=source_id_type,json=sourceIdType,proto3" json:"source_id_type,omitempty"`
	SourceIdValue        uint32                 `protobuf:"varint,35,opt,name=source_id_value,json=sourceIdValue,proto3" json:"source_id_value,omitempty"`
	SampleSequence       uint32                 `protobuf:"varint,36,opt,name=sample_sequence,json=sampleSequence,proto3" json:"sample_sequence,omitempty"`
	SamplePool           uint64                 `protobuf:"varint,37,opt,name=sample_pool,json=samplePool,proto3" json:"sample_pool,omitempty"`
	ExporterDrops        uint64                 `protobuf:"varint,38,opt,name=exporter_drops,json=exporterDrops,proto3" json:"exporter_drops,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NormalizedRecord) Reset() {
	*x = NormalizedRecord{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedRecord) ProtoMessage() {}

func (x *NormalizedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedRecord.ProtoReflect.Descriptor instead.
func (*NormalizedRecord) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizedRecord) GetRecordIndex() uint32 {
	if x != nil {
		return x.RecordIndex
	}
	return 0
}

func (x *NormalizedRecord) GetEventTimeUnixMs() int64 {
	if x != nil {
		return x.EventTimeUnixMs
	}
	return 0
}

func (x *NormalizedRecord) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NormalizedRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *NormalizedRecord) GetObservationIfIndex() uint32 {
	if x != nil {
		return x.ObservationIfIndex
	}
	return 0
}

func (x *NormalizedRecord) GetObservationDirection() uint32 {
	if x != nil {
		return x.ObservationDirection
	}
	return 0
}

func (x *NormalizedRecord) GetInIf() uint32 {
	if x != nil {
		return x.InIf
	}
	return 0
}

func (x *NormalizedRecord) GetOutIf() uint32 {
	if x != nil {
		return x.OutIf
	}
	return 0
}

func (x *NormalizedRecord) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *NormalizedRecord) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *NormalizedRecord) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *NormalizedRecord) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *NormalizedRecord) GetIpProto() uint32 {
	if x != nil {
		return x.IpProto
	}
	return 0
}

func (x *NormalizedRecord) GetTcpFlags() uint32 {
	if x != nil {
		return x.TcpFlags
	}
	return 0
}

func (x *NormalizedRecord) GetRawBytes() uint64 {
	if x != nil {
		return x.RawBytes
	}
	return 0
}

func (x *NormalizedRecord) GetRawPackets() uint64 {
	if x != nil {
		return x.RawPackets
	}
	return 0
}

func (x *NormalizedRecord) GetSamplingMode() uint32 {
	if x != nil {
		return x.SamplingMode
	}
	return 0
}

func (x *NormalizedRecord) GetSamplingRate() uint64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *NormalizedRecord) GetEstimatedBytes() uint64 {
	if x != nil {
		return x.EstimatedBytes
	}
	return 0
}

func (x *NormalizedRecord) GetEstimatedPackets() uint64 {
	if x != nil {
		return x.EstimatedPackets
	}
	return 0
}

func (x *NormalizedRecord) GetFlowDurationMs() uint64 {
	if x != nil {
		return x.FlowDurationMs
	}
	return 0
}

func (x *NormalizedRecord) GetQualityFlags() uint64 {
	if x != nil {
		return x.QualityFlags
	}
	return 0
}

func (x *NormalizedRecord) GetSrcAs() uint32 {
	if x != nil {
		return x.SrcAs
	}
	return 0
}

func (x *NormalizedRecord) GetDstAs() uint32 {
	if x != nil {
		return x.DstAs
	}
	return 0
}

func (x *NormalizedRecord) GetSourceIdType() uint32 {
	if x != nil {
		return x.SourceIdType
	}
	return 0
}

func (x *NormalizedRecord) GetSourceIdValue() uint32 {
	if x != nil {
		return x.SourceIdValue
	}
	return 0
}

func (x *NormalizedRecord) GetSampleSequence() uint32 {
	if x != nil {
		return x.SampleSequence
	}
	return 0
}

func (x *NormalizedRecord) GetSamplePool() uint64 {
	if x != nil {
		return x.SamplePool
	}
	return 0
}

func (x *NormalizedRecord) GetExporterDrops() uint64 {
	if x != nil {
		return x.ExporterDrops
	}
	return 0
}

// CollectState is the durable decoder state for one transport source,
// protocol and observation domain. The compacted Kafka key is state_key.
type CollectState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StateSchemaVersion  uint32                 `protobuf:"varint,1,opt,name=state_schema_version,json=stateSchemaVersion,proto3" json:"state_schema_version,omitempty"`
	StateId             []byte                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	StateKey            []byte                 `protobuf:"bytes,3,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	DatagramId          []byte                 `protobuf:"bytes,4,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectorId         string                 `protobuf:"bytes,6,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ExporterId          string                 `protobuf:"bytes,7,opt,name=exporter_id,json=exporterId,proto3" json:"exporter_id,omitempty"`
	RegistryVersion     uint64                 `protobuf:"varint,8,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	ReceivedAtUnixMs    int64                  `protobuf:"varint,9,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Protocol            uint32                 `protobuf:"varint,10,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp            []byte                 `protobuf:"bytes,11,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ObservationDomainId uint64                 `protobuf:"varint,12,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	TemplatesJson       []byte                 `protobuf:"bytes,13,opt,name=templates_json,json=templatesJson,proto3" json:"templates_json,omitempty"`
	SamplingRatesJson   []byte                 `protobuf:"bytes,14,opt,name=sampling_rates_json,json=samplingRatesJson,proto3" json:"sampling_rates_json,omitempty"`
	PayloadSha256       []byte                 `protobuf:"bytes,15,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CollectState) Reset() {
	*x = CollectState{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectState) ProtoMessage() {}

func (x *CollectState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectState.ProtoReflect.Descriptor instead.
func (*CollectState) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{2}
}

func (x *CollectState) GetStateSchemaVersion() uint32 {
	if x != nil {
		return x.StateSchemaVersion
	}
	return 0
}

func (x *CollectState) GetStateId() []byte {
	if x != nil {
		return x.StateId
	}
	return nil
}

func (x *CollectState) GetStateKey() []byte {
	if x != nil {
		return x.StateKey
	}
	return nil
}

func (x *CollectState) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *CollectState) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CollectState) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *CollectState) GetExporterId() string {
	if x != nil {
		return x.ExporterId
	}
	return ""
}

func (x *CollectState) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

func (x *CollectState) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *CollectState) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *CollectState) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *CollectState) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *CollectState) GetTemplatesJson() []byte {
	if x != nil {
		return x.TemplatesJson
	}
	return nil
}

func (x *CollectState) GetSamplingRatesJson() []byte {
	if x != nil {
		return x.SamplingRatesJson
	}
	return nil
}

func (x *CollectState) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

var File_internal_flowcollect_flowpb_normalized_proto protoreflect.FileDescriptor

const file_internal_flowcollect_flowpb_normalized_proto_rawDesc = "" +
	"\n" +
	",internal/flowcollect/flowpb/normalized.proto\x12\x10watchdog.flow.v1\"\xa5\x06\n" +
	"\x15NormalizedRecordBatch\x120\n" +
	"\x14batch_schema_version\x18\x01 \x01(\rR\x12batchSchemaVersion\x12.\n" +
	"\x13normalized_batch_id\x18\x02 \x01(\fR\x11normalizedBatchId\x12\x1f\n" +
	"\vdatagram_id\x18\x03 \x01(\fR\n" +
	"datagramId\x12#\n" +
	"\rvirtual_shard\x18\x04 \x01(\rR\fvirtualShard\x122\n" +
	"\x15partition_map_version\x18\x05 \x01(\rR\x13partitionMapVersion\x12-\n" +
	"\x12physical_partition\x18\x06 \x01(\rR\x11physicalPartition\x12+\n" +
	"\x11replay_generation\x18\a \x01(\rR\x10replayGeneration\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12!\n" +
	"\fcollector_id\x18\t \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vexporter_id\x18\n" +
	" \x01(\tR\n" +
	"exporterId\x12)\n" +
	"\x10registry_version\x18\v \x01(\x04R\x0fregistryVersion\x12-\n" +
	"\x13received_at_unix_ms\x18\f \x01(\x03R\x10receivedAtUnixMs\x12\x1a\n" +
	"\bprotocol\x18\r \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x0e \x01(\fR\bsourceIp\x122\n" +
	"\x15observation_domain_id\x18\x0f \x01(\x04R\x13observationDomainId\x12<\n" +
	"\arecords\x18\x10 \x03(\v2\".watchdog.flow.v1.NormalizedRecordR\arecords\x12 \n" +
	"\fsub_agent_id\x18  \x01(\rR\n" +
	"subAgentId\x12+\n" +
	"\x11datagram_sequence\x18! \x01(\rR\x10datagramSequence\x12\x19\n" +
	"\bagent_ip\x18\" \x01(\fR\aagentIpJ\x04\b\x11\x10 \"\xeb\a\n" +
	"\x10NormalizedRecord\x12!\n" +
	"\frecord_index\x18\x01 \x01(\rR\vrecordIndex\x12+\n" +
	"\x12event_time_unix_ms\x18\x02 \x01(\x03R\x0feventTimeUnixMs\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x120\n" +
	"\x14observation_if_index\x18\x05 \x01(\rR\x12observationIfIndex\x123\n" +
	"\x15observation_direction\x18\x06 \x01(\rR\x14observationDirection\x12\x13\n" +
	"\x05in_if\x18\a \x01(\rR\x04inIf\x12\x15\n" +
	"\x06out_if\x18\b \x01(\rR\x05outIf\x12\x15\n" +
	"\x06src_ip\x18\t \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\n" +
	" \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\v \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\f \x01(\rR\adstPort\x12\x19\n" +
	"\bip_proto\x18\r \x01(\rR\aipProto\x12\x1b\n" +
	"\ttcp_flags\x18\x0e \x01(\rR\btcpFlags\x12\x1b\n" +
	"\traw_bytes\x18\x0f \x01(\x04R\brawBytes\x12\x1f\n" +
	"\vraw_packets\x18\x10 \x01(\x04R\n" +
	"rawPackets\x12#\n" +
	"\rsampling_mode\x18\x11 \x01(\rR\fsamplingMode\x12#\n" +
	"\rsampling_rate\x18\x12 \x01(\x04R\fsamplingRate\x12'\n" +
	"\x0festimated_bytes\x18\x13 \x01(\x04R\x0eestimatedBytes\x12+\n" +
	"\x11estimated_packets\x18\x14 \x01(\x04R\x10estimatedPackets\x12(\n" +
	"\x10flow_duration_ms\x18\x15 \x01(\x04R\x0eflowDurationMs\x12#\n" +
	"\rquality_flags\x18\x16 \x01(\x04R\fqualityFlags\x12\x15\n" +
	"\x06src_as\x18  \x01(\rR\x05srcAs\x12\x15\n" +
	"\x06dst_as\x18! \x01(\rR\x05dstAs\x12$\n" +
	"\x0esource_id_type\x18\" \x01(\rR\fsourceIdType\x12&\n" +
	"\x0fsource_id_value\x18# \x01(\rR\rsourceIdValue\x12'\n" +
	"\x0fsample_sequence\x18$ \x01(\rR\x0esampleSequence\x12\x1f\n" +
	"\vsample_pool\x18% \x01(\x04R\n" +
	"samplePool\x12%\n" +
	"\x0eexporter_drops\x18& \x01(\x04R\rexporterDropsJ\x04\b\x17\x10 \"\xbf\x04\n" +
	"\fCollectState\x120\n" +
	"\x14state_schema_version\x18\x01 \x01(\rR\x12stateSchemaVersion\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\fR\astateId\x12\x1b\n" +
	"\tstate_key\x18\x03 \x01(\fR\bstateKey\x12\x1f\n" +
	"\vdatagram_id\x18\x04 \x01(\fR\n" +
	"datagramId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12!\n" +
	"\fcollector_id\x18\x06 \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vexporter_id\x18\a \x01(\tR\n" +
	"exporterId\x12)\n" +
	"\x10registry_version\x18\b \x01(\x04R\x0fregistryVersion\x12-\n" +
	"\x13received_at_unix_ms\x18\t \x01(\x03R\x10receivedAtUnixMs\x12\x1a\n" +
	"\bprotocol\x18\n" +
	" \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\v \x01(\fR\bsourceIp\x122\n" +
	"\x15observation_domain_id\x18\f \x01(\x04R\x13observationDomainId\x12%\n" +
	"\x0etemplates_json\x18\r \x01(\fR\rtemplatesJson\x12.\n" +
	"\x13sampling_rates_json\x18\x0e \x01(\fR\x11samplingRatesJson\x12%\n" +
	"\x0epayload_sha256\x18\x0f \x01(\fR\rpayloadSha256BCZAgithub.com/cloudcache/watchdog/internal/flowcollect/flowpb;flowpbb\x06proto3"

var (
	file_internal_flowcollect_flowpb_normalized_proto_rawDescOnce sync.Once
	file_internal_flowcollect_flowpb_normalized_proto_rawDescData []byte
)

func file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP() []byte {
	file_internal_flowcollect_flowpb_normalized_proto_rawDescOnce.Do(func() {
		file_internal_flowcollect_flowpb_normalized_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_flowcollect_flowpb_normalized_proto_rawDesc), len(file_internal_flowcollect_flowpb_normalized_proto_rawDesc)))
	})
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescData
}

var file_internal_flowcollect_flowpb_normalized_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_flowcollect_flowpb_normalized_proto_goTypes = []any{
	(*NormalizedRecordBatch)(nil), // 0: watchdog.flow.v1.NormalizedRecordBatch
	(*NormalizedRecord)(nil),      // 1: watchdog.flow.v1.NormalizedRecord
	(*CollectState)(nil),          // 2: watchdog.flow.v1.CollectState
}
var file_internal_flowcollect_flowpb_normalized_proto_depIdxs = []int32{
	1, // 0: watchdog.flow.v1.NormalizedRecordBatch.records:type_name -> watchdog.flow.v1.NormalizedRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_flowcollect_flowpb_normalized_proto_init() }
func file_internal_flowcollect_flowpb_normalized_proto_init() {
	if File_internal_flowcollect_flowpb_normalized_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_flowcollect_flowpb_normalized_proto_rawDesc), len(file_internal_flowcollect_flowpb_normalized_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_flowcollect_flowpb_normalized_proto_goTypes,
		DependencyIndexes: file_internal_flowcollect_flowpb_normalized_proto_depIdxs,
		MessageInfos:      file_internal_flowcollect_flowpb_normalized_proto_msgTypes,
	}.Build()
	File_internal_flowcollect_flowpb_normalized_proto = out.File
	file_internal_flowcollect_flowpb_normalized_proto_goTypes = nil
	file_internal_flowcollect_flowpb_normalized_proto_depIdxs = nil
}
