// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/flowcollect/flowpb/normalized.proto

package flowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NormalizedRecordBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BatchSchemaVersion  uint32                 `protobuf:"varint,1,opt,name=batch_schema_version,json=batchSchemaVersion,proto3" json:"batch_schema_version,omitempty"`
	NormalizedBatchId   []byte                 `protobuf:"bytes,2,opt,name=normalized_batch_id,json=normalizedBatchId,proto3" json:"normalized_batch_id,omitempty"`
	DatagramId          []byte                 `protobuf:"bytes,3,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	VirtualShard        uint32                 `protobuf:"varint,4,opt,name=virtual_shard,json=virtualShard,proto3" json:"virtual_shard,omitempty"`
	PartitionMapVersion uint32                 `protobuf:"varint,5,opt,name=partition_map_version,json=partitionMapVersion,proto3" json:"partition_map_version,omitempty"`
	PhysicalPartition   uint32                 `protobuf:"varint,6,opt,name=physical_partition,json=physicalPartition,proto3" json:"physical_partition,omitempty"`
	ReplayGeneration    uint32                 `protobuf:"varint,7,opt,name=replay_generation,json=replayGeneration,proto3" json:"replay_generation,omitempty"`
	TenantId            string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectorId         string                 `protobuf:"bytes,9,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ExporterId          string                 `protobuf:"bytes,10,opt,name=exporter_id,json=exporterId,proto3" json:"exporter_id,omitempty"`
	RegistryVersion     uint64                 `protobuf:"varint,11,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	ReceivedAtUnixMs    int64                  `protobuf:"varint,12,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Protocol            uint32                 `protobuf:"varint,13,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp            []byte                 `protobuf:"bytes,14,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ObservationDomainId uint64                 `protobuf:"varint,15,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	Records             []*NormalizedRecord    `protobuf:"bytes,16,rep,name=records,proto3" json:"records,omitempty"`
	// sFlow datagram state. Per-sample state remains on each record.
	SubAgentId       uint32 `protobuf:"varint,32,opt,name=sub_agent_id,json=subAgentId,proto3" json:"sub_agent_id,omitempty"`
	DatagramSequence uint32 `protobuf:"varint,33,opt,name=datagram_sequence,json=datagramSequence,proto3" json:"datagram_sequence,omitempty"`
	AgentIp          []byte `protobuf:"bytes,34,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	ExporterEpoch    uint64 `protobuf:"varint,35,opt,name=exporter_epoch,json=exporterEpoch,proto3" json:"exporter_epoch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NormalizedRecordBatch) Reset() {
	*x = NormalizedRecordBatch{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedRecordBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedRecordBatch) ProtoMessage() {}

func (x *NormalizedRecordBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedRecordBatch.ProtoReflect.Descriptor instead.
func (*NormalizedRecordBatch) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedRecordBatch) GetBatchSchemaVersion() uint32 {
	if x != nil {
		return x.BatchSchemaVersion
	}
	return 0
}

func (x *NormalizedRecordBatch) GetNormalizedBatchId() []byte {
	if x != nil {
		return x.NormalizedBatchId
	}
	return nil
}

func (x *NormalizedRecordBatch) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *NormalizedRecordBatch) GetVirtualShard() uint32 {
	if x != nil {
		return x.VirtualShard
	}
	return 0
}

func (x *NormalizedRecordBatch) GetPartitionMapVersion() uint32 {
	if x != nil {
		return x.PartitionMapVersion
	}
	return 0
}

func (x *NormalizedRecordBatch) GetPhysicalPartition() uint32 {
	if x != nil {
		return x.PhysicalPartition
	}
	return 0
}

func (x *NormalizedRecordBatch) GetReplayGeneration() uint32 {
	if x != nil {
		return x.ReplayGeneration
	}
	return 0
}

func (x *NormalizedRecordBatch) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NormalizedRecordBatch) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *NormalizedRecordBatch) GetExporterId() string {
	if x != nil {
		return x.ExporterId
	}
	return ""
}

func (x *NormalizedRecordBatch) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

func (x *NormalizedRecordBatch) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *NormalizedRecordBatch) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *NormalizedRecordBatch) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *NormalizedRecordBatch) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *NormalizedRecordBatch) GetRecords() []*NormalizedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *NormalizedRecordBatch) GetSubAgentId() uint32 {
	if x != nil {
		return x.SubAgentId
	}
	return 0
}

func (x *NormalizedRecordBatch) GetDatagramSequence() uint32 {
	if x != nil {
		return x.DatagramSequence
	}
	return 0
}

func (x *NormalizedRecordBatch) GetAgentIp() []byte {
	if x != nil {
		return x.AgentIp
	}
	return nil
}

func (x *NormalizedRecordBatch) GetExporterEpoch() uint64 {
	if x != nil {
		return x.ExporterEpoch
	}
	return 0
}

type NormalizedRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RecordIndex          uint32                 `protobuf:"varint,1,opt,name=record_index,json=recordIndex,proto3" json:"record_index,omitempty"`
	EventTimeUnixMs      int64                  `protobuf:"varint,2,opt,name=event_time_unix_ms,json=eventTimeUnixMs,proto3" json:"event_time_unix_ms,omitempty"`
	TargetId             string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DeviceId             string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ObservationIfIndex   uint32                 `protobuf:"varint,5,opt,name=observation_if_index,json=observationIfIndex,proto3" json:"observation_if_index,omitempty"`
	ObservationDirection uint32                 `protobuf:"varint,6,opt,name=observation_direction,json=observationDirection,proto3" json:"observation_direction,omitempty"`
	InIf                 uint32                 `protobuf:"varint,7,opt,name=in_if,json=inIf,proto3" json:"in_if,omitempty"`
	OutIf                uint32                 `protobuf:"varint,8,opt,name=out_if,json=outIf,proto3" json:"out_if,omitempty"`
	SrcIp                []byte                 `protobuf:"bytes,9,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp                []byte                 `protobuf:"bytes,10,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort              uint32                 `protobuf:"varint,11,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort              uint32                 `protobuf:"varint,12,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	IpProto              uint32                 `protobuf:"varint,13,opt,name=ip_proto,json=ipProto,proto3" json:"ip_proto,omitempty"`
	TcpFlags             uint32                 `protobuf:"varint,14,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	RawBytes             uint64                 `protobuf:"varint,15,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	RawPackets           uint64                 `protobuf:"varint,16,opt,name=raw_packets,json=rawPackets,proto3" json:"raw_packets,omitempty"`
	SamplingMode         uint32                 `protobuf:"varint,17,opt,name=sampling_mode,json=samplingMode,proto3" json:"sampling_mode,omitempty"`
	SamplingRate         uint64                 `protobuf:"varint,18,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	EstimatedBytes       uint64                 `protobuf:"varint,19,opt,name=estimated_bytes,json=estimatedBytes,proto3" json:"estimated_bytes,omitempty"`
	EstimatedPackets     uint64                 `protobuf:"varint,20,opt,name=estimated_packets,json=estimatedPackets,proto3" json:"estimated_packets,omitempty"`
	FlowDurationMs       uint64                 `protobuf:"varint,21,opt,name=flow_duration_ms,json=flowDurationMs,proto3" json:"flow_duration_ms,omitempty"`
	QualityFlags         uint64                 `protobuf:"varint,22,opt,name=quality_flags,json=qualityFlags,proto3" json:"quality_flags,omitempty"`
	SrcAs                uint32                 `protobuf:"varint,32,opt,name=src_as,json=srcAs,proto3" json:"src_as,omitempty"`
	DstAs                uint32                 `protobuf:"varint,33,opt,name=dst_as,json=dstAs,proto3" json:"dst_as,omitempty"`
	SourceIdType         uint32                 `protobuf:"varint,34,opt,name=source_id_type,json=sourceIdType,proto3" json:"source_id_type,omitempty"`
	SourceIdValue        uint32                 `protobuf:"varint,35,opt,name=source_id_value,json=sourceIdValue,proto3" json:"source_id_value,omitempty"`
	SampleSequence       uint32                 `protobuf:"varint,36,opt,name=sample_sequence,json=sampleSequence,proto3" json:"sample_sequence,omitempty"`
	SamplePool           uint64                 `protobuf:"varint,37,opt,name=sample_pool,json=samplePool,proto3" json:"sample_pool,omitempty"`
	ExporterDrops        uint64                 `protobuf:"varint,38,opt,name=exporter_drops,json=exporterDrops,proto3" json:"exporter_drops,omitempty"`
	SampleIndex          uint32                 `protobuf:"varint,39,opt,name=sample_index,json=sampleIndex,proto3" json:"sample_index,omitempty"`
	QualityEpoch         uint64                 `protobuf:"varint,40,opt,name=quality_epoch,json=qualityEpoch,proto3" json:"quality_epoch,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NormalizedRecord) Reset() {
	*x = NormalizedRecord{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedRecord) ProtoMessage() {}

func (x *NormalizedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedRecord.ProtoReflect.Descriptor instead.
func (*NormalizedRecord) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizedRecord) GetRecordIndex() uint32 {
	if x != nil {
		return x.RecordIndex
	}
	return 0
}

func (x *NormalizedRecord) GetEventTimeUnixMs() int64 {
	if x != nil {
		return x.EventTimeUnixMs
	}
	return 0
}

func (x *NormalizedRecord) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NormalizedRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *NormalizedRecord) GetObservationIfIndex() uint32 {
	if x != nil {
		return x.ObservationIfIndex
	}
	return 0
}

func (x *NormalizedRecord) GetObservationDirection() uint32 {
	if x != nil {
		return x.ObservationDirection
	}
	return 0
}

func (x *NormalizedRecord) GetInIf() uint32 {
	if x != nil {
		return x.InIf
	}
	return 0
}

func (x *NormalizedRecord) GetOutIf() uint32 {
	if x != nil {
		return x.OutIf
	}
	return 0
}

func (x *NormalizedRecord) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *NormalizedRecord) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *NormalizedRecord) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *NormalizedRecord) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *NormalizedRecord) GetIpProto() uint32 {
	if x != nil {
		return x.IpProto
	}
	return 0
}

func (x *NormalizedRecord) GetTcpFlags() uint32 {
	if x != nil {
		return x.TcpFlags
	}
	return 0
}

func (x *NormalizedRecord) GetRawBytes() uint64 {
	if x != nil {
		return x.RawBytes
	}
	return 0
}

func (x *NormalizedRecord) GetRawPackets() uint64 {
	if x != nil {
		return x.RawPackets
	}
	return 0
}

func (x *NormalizedRecord) GetSamplingMode() uint32 {
	if x != nil {
		return x.SamplingMode
	}
	return 0
}

func (x *NormalizedRecord) GetSamplingRate() uint64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *NormalizedRecord) GetEstimatedBytes() uint64 {
	if x != nil {
		return x.EstimatedBytes
	}
	return 0
}

func (x *NormalizedRecord) GetEstimatedPackets() uint64 {
	if x != nil {
		return x.EstimatedPackets
	}
	return 0
}

func (x *NormalizedRecord) GetFlowDurationMs() uint64 {
	if x != nil {
		return x.FlowDurationMs
	}
	return 0
}

func (x *NormalizedRecord) GetQualityFlags() uint64 {
	if x != nil {
		return x.QualityFlags
	}
	return 0
}

func (x *NormalizedRecord) GetSrcAs() uint32 {
	if x != nil {
		return x.SrcAs
	}
	return 0
}

func (x *NormalizedRecord) GetDstAs() uint32 {
	if x != nil {
		return x.DstAs
	}
	return 0
}

func (x *NormalizedRecord) GetSourceIdType() uint32 {
	if x != nil {
		return x.SourceIdType
	}
	return 0
}

func (x *NormalizedRecord) GetSourceIdValue() uint32 {
	if x != nil {
		return x.SourceIdValue
	}
	return 0
}

func (x *NormalizedRecord) GetSampleSequence() uint32 {
	if x != nil {
		return x.SampleSequence
	}
	return 0
}

func (x *NormalizedRecord) GetSamplePool() uint64 {
	if x != nil {
		return x.SamplePool
	}
	return 0
}

func (x *NormalizedRecord) GetExporterDrops() uint64 {
	if x != nil {
		return x.ExporterDrops
	}
	return 0
}

func (x *NormalizedRecord) GetSampleIndex() uint32 {
	if x != nil {
		return x.SampleIndex
	}
	return 0
}

func (x *NormalizedRecord) GetQualityEpoch() uint64 {
	if x != nil {
		return x.QualityEpoch
	}
	return 0
}

// CollectState is the durable decoder state for one transport source,
// protocol and observation domain. The compacted Kafka key is state_key.
type CollectState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StateSchemaVersion  uint32                 `protobuf:"varint,1,opt,name=state_schema_version,json=stateSchemaVersion,proto3" json:"state_schema_version,omitempty"`
	StateId             []byte                 `protobuf:"bytes,2,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	StateKey            []byte                 `protobuf:"bytes,3,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	DatagramId          []byte                 `protobuf:"bytes,4,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectorId         string                 `protobuf:"bytes,6,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ExporterId          string                 `protobuf:"bytes,7,opt,name=exporter_id,json=exporterId,proto3" json:"exporter_id,omitempty"`
	RegistryVersion     uint64                 `protobuf:"varint,8,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	ReceivedAtUnixMs    int64                  `protobuf:"varint,9,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Protocol            uint32                 `protobuf:"varint,10,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp            []byte                 `protobuf:"bytes,11,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ObservationDomainId uint64                 `protobuf:"varint,12,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	TemplatesJson       []byte                 `protobuf:"bytes,13,opt,name=templates_json,json=templatesJson,proto3" json:"templates_json,omitempty"`
	SamplingRatesJson   []byte                 `protobuf:"bytes,14,opt,name=sampling_rates_json,json=samplingRatesJson,proto3" json:"sampling_rates_json,omitempty"`
	PayloadSha256       []byte                 `protobuf:"bytes,15,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	// state_identity_key is stable across collector ownership changes. state_key
	// additionally contains ownership_epoch so a fenced old owner cannot
	// overwrite the current owner's compacted checkpoint.
	StateIdentityKey []byte `protobuf:"bytes,16,opt,name=state_identity_key,json=stateIdentityKey,proto3" json:"state_identity_key,omitempty"`
	OwnershipEpoch   uint64 `protobuf:"varint,17,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	StateGeneration  uint64 `protobuf:"varint,18,opt,name=state_generation,json=stateGeneration,proto3" json:"state_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectState) Reset() {
	*x = CollectState{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectState) ProtoMessage() {}

func (x *CollectState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectState.ProtoReflect.Descriptor instead.
func (*CollectState) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{2}
}

func (x *CollectState) GetStateSchemaVersion() uint32 {
	if x != nil {
		return x.StateSchemaVersion
	}
	return 0
}

func (x *CollectState) GetStateId() []byte {
	if x != nil {
		return x.StateId
	}
	return nil
}

func (x *CollectState) GetStateKey() []byte {
	if x != nil {
		return x.StateKey
	}
	return nil
}

func (x *CollectState) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *CollectState) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CollectState) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *CollectState) GetExporterId() string {
	if x != nil {
		return x.ExporterId
	}
	return ""
}

func (x *CollectState) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

func (x *CollectState) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *CollectState) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *CollectState) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *CollectState) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *CollectState) GetTemplatesJson() []byte {
	if x != nil {
		return x.TemplatesJson
	}
	return nil
}

func (x *CollectState) GetSamplingRatesJson() []byte {
	if x != nil {
		return x.SamplingRatesJson
	}
	return nil
}

func (x *CollectState) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

func (x *CollectState) GetStateIdentityKey() []byte {
	if x != nil {
		return x.StateIdentityKey
	}
	return nil
}

func (x *CollectState) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *CollectState) GetStateGeneration() uint64 {
	if x != nil {
		return x.StateGeneration
	}
	return 0
}

// DecodeFailure is a terminal, Kafka-acknowledged outcome for a durable WAL
// datagram. payload is empty unless explicitly enabled for restricted diagnosis.
type DecodeFailure struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FailureSchemaVersion uint32                 `protobuf:"varint,1,opt,name=failure_schema_version,json=failureSchemaVersion,proto3" json:"failure_schema_version,omitempty"`
	EventId              []byte                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DatagramId           []byte                 `protobuf:"bytes,3,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	TenantId             string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectorId          string                 `protobuf:"bytes,5,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ExporterId           string                 `protobuf:"bytes,6,opt,name=exporter_id,json=exporterId,proto3" json:"exporter_id,omitempty"`
	RegistryVersion      uint64                 `protobuf:"varint,7,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	ReceivedAtUnixMs     int64                  `protobuf:"varint,8,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Protocol             uint32                 `protobuf:"varint,9,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp             []byte                 `protobuf:"bytes,10,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ObservationDomainId  uint64                 `protobuf:"varint,11,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	ErrorCode            string                 `protobuf:"bytes,12,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorSummary         string                 `protobuf:"bytes,13,opt,name=error_summary,json=errorSummary,proto3" json:"error_summary,omitempty"`
	Attempts             uint32                 `protobuf:"varint,14,opt,name=attempts,proto3" json:"attempts,omitempty"`
	PayloadSha256        []byte                 `protobuf:"bytes,15,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	Payload              []byte                 `protobuf:"bytes,16,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadTruncated     bool                   `protobuf:"varint,17,opt,name=payload_truncated,json=payloadTruncated,proto3" json:"payload_truncated,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DecodeFailure) Reset() {
	*x = DecodeFailure{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeFailure) ProtoMessage() {}

func (x *DecodeFailure) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeFailure.ProtoReflect.Descriptor instead.
func (*DecodeFailure) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{3}
}

func (x *DecodeFailure) GetFailureSchemaVersion() uint32 {
	if x != nil {
		return x.FailureSchemaVersion
	}
	return 0
}

func (x *DecodeFailure) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *DecodeFailure) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *DecodeFailure) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DecodeFailure) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *DecodeFailure) GetExporterId() string {
	if x != nil {
		return x.ExporterId
	}
	return ""
}

func (x *DecodeFailure) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

func (x *DecodeFailure) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *DecodeFailure) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *DecodeFailure) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *DecodeFailure) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *DecodeFailure) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DecodeFailure) GetErrorSummary() string {
	if x != nil {
		return x.ErrorSummary
	}
	return ""
}

func (x *DecodeFailure) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DecodeFailure) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

func (x *DecodeFailure) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DecodeFailure) GetPayloadTruncated() bool {
	if x != nil {
		return x.PayloadTruncated
	}
	return false
}

// QuarantineEvent is rate-limited metadata for an unregistered source. It
// never carries the datagram payload and has no tenant supplied by the packet.
type QuarantineEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventSchemaVersion  uint32                 `protobuf:"varint,1,opt,name=event_schema_version,json=eventSchemaVersion,proto3" json:"event_schema_version,omitempty"`
	EventId             []byte                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CollectorId         string                 `protobuf:"bytes,3,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ReceivedAtUnixMs    int64                  `protobuf:"varint,4,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Protocol            uint32                 `protobuf:"varint,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp            []byte                 `protobuf:"bytes,6,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ObservationDomainId uint64                 `protobuf:"varint,7,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	ReasonCode          string                 `protobuf:"bytes,8,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	PayloadBytes        uint32                 `protobuf:"varint,9,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	PayloadSha256       []byte                 `protobuf:"bytes,10,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QuarantineEvent) Reset() {
	*x = QuarantineEvent{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuarantineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuarantineEvent) ProtoMessage() {}

func (x *QuarantineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuarantineEvent.ProtoReflect.Descriptor instead.
func (*QuarantineEvent) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{4}
}

func (x *QuarantineEvent) GetEventSchemaVersion() uint32 {
	if x != nil {
		return x.EventSchemaVersion
	}
	return 0
}

func (x *QuarantineEvent) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *QuarantineEvent) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *QuarantineEvent) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *QuarantineEvent) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *QuarantineEvent) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *QuarantineEvent) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *QuarantineEvent) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *QuarantineEvent) GetPayloadBytes() uint32 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

func (x *QuarantineEvent) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

// Quality state is local durability metadata. It is protobuf-framed in an
// append journal and periodically compacted into QualityStateSnapshot.
type QualityExporterKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp      []byte                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SequenceScope uint64                 `protobuf:"varint,3,opt,name=sequence_scope,json=sequenceScope,proto3" json:"sequence_scope,omitempty"`
	AgentIp       []byte                 `protobuf:"bytes,4,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	SubAgentId    uint32                 `protobuf:"varint,5,opt,name=sub_agent_id,json=subAgentId,proto3" json:"sub_agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityExporterKey) Reset() {
	*x = QualityExporterKey{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityExporterKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityExporterKey) ProtoMessage() {}

func (x *QualityExporterKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityExporterKey.ProtoReflect.Descriptor instead.
func (*QualityExporterKey) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{5}
}

func (x *QualityExporterKey) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *QualityExporterKey) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *QualityExporterKey) GetSequenceScope() uint64 {
	if x != nil {
		return x.SequenceScope
	}
	return 0
}

func (x *QualityExporterKey) GetAgentIp() []byte {
	if x != nil {
		return x.AgentIp
	}
	return nil
}

func (x *QualityExporterKey) GetSubAgentId() uint32 {
	if x != nil {
		return x.SubAgentId
	}
	return 0
}

type QualityWindows struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TemplateUntilUnixMs   int64                  `protobuf:"varint,1,opt,name=template_until_unix_ms,json=templateUntilUnixMs,proto3" json:"template_until_unix_ms,omitempty"`
	GapUntilUnixMs        int64                  `protobuf:"varint,2,opt,name=gap_until_unix_ms,json=gapUntilUnixMs,proto3" json:"gap_until_unix_ms,omitempty"`
	PoolResetUntilUnixMs  int64                  `protobuf:"varint,3,opt,name=pool_reset_until_unix_ms,json=poolResetUntilUnixMs,proto3" json:"pool_reset_until_unix_ms,omitempty"`
	RateChangeUntilUnixMs int64                  `protobuf:"varint,4,opt,name=rate_change_until_unix_ms,json=rateChangeUntilUnixMs,proto3" json:"rate_change_until_unix_ms,omitempty"`
	RestartUntilUnixMs    int64                  `protobuf:"varint,5,opt,name=restart_until_unix_ms,json=restartUntilUnixMs,proto3" json:"restart_until_unix_ms,omitempty"`
	OutOfOrderUntilUnixMs int64                  `protobuf:"varint,6,opt,name=out_of_order_until_unix_ms,json=outOfOrderUntilUnixMs,proto3" json:"out_of_order_until_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QualityWindows) Reset() {
	*x = QualityWindows{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityWindows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityWindows) ProtoMessage() {}

func (x *QualityWindows) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityWindows.ProtoReflect.Descriptor instead.
func (*QualityWindows) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{6}
}

func (x *QualityWindows) GetTemplateUntilUnixMs() int64 {
	if x != nil {
		return x.TemplateUntilUnixMs
	}
	return 0
}

func (x *QualityWindows) GetGapUntilUnixMs() int64 {
	if x != nil {
		return x.GapUntilUnixMs
	}
	return 0
}

func (x *QualityWindows) GetPoolResetUntilUnixMs() int64 {
	if x != nil {
		return x.PoolResetUntilUnixMs
	}
	return 0
}

func (x *QualityWindows) GetRateChangeUntilUnixMs() int64 {
	if x != nil {
		return x.RateChangeUntilUnixMs
	}
	return 0
}

func (x *QualityWindows) GetRestartUntilUnixMs() int64 {
	if x != nil {
		return x.RestartUntilUnixMs
	}
	return 0
}

func (x *QualityWindows) GetOutOfOrderUntilUnixMs() int64 {
	if x != nil {
		return x.OutOfOrderUntilUnixMs
	}
	return 0
}

type QualityExporterState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Key               *QualityExporterKey    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Initialized       bool                   `protobuf:"varint,2,opt,name=initialized,proto3" json:"initialized,omitempty"`
	ExpectedSequence  uint32                 `protobuf:"varint,3,opt,name=expected_sequence,json=expectedSequence,proto3" json:"expected_sequence,omitempty"`
	Uptime            uint32                 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	UptimeValid       bool                   `protobuf:"varint,5,opt,name=uptime_valid,json=uptimeValid,proto3" json:"uptime_valid,omitempty"`
	LastSeenUnixMs    int64                  `protobuf:"varint,6,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	Epoch             uint64                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SamplingEpoch     uint64                 `protobuf:"varint,8,opt,name=sampling_epoch,json=samplingEpoch,proto3" json:"sampling_epoch,omitempty"`
	SamplingRate      uint64                 `protobuf:"varint,9,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	SamplingRateKnown bool                   `protobuf:"varint,10,opt,name=sampling_rate_known,json=samplingRateKnown,proto3" json:"sampling_rate_known,omitempty"`
	Windows           *QualityWindows        `protobuf:"bytes,11,opt,name=windows,proto3" json:"windows,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QualityExporterState) Reset() {
	*x = QualityExporterState{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityExporterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityExporterState) ProtoMessage() {}

func (x *QualityExporterState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityExporterState.ProtoReflect.Descriptor instead.
func (*QualityExporterState) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{7}
}

func (x *QualityExporterState) GetKey() *QualityExporterKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *QualityExporterState) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *QualityExporterState) GetExpectedSequence() uint32 {
	if x != nil {
		return x.ExpectedSequence
	}
	return 0
}

func (x *QualityExporterState) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *QualityExporterState) GetUptimeValid() bool {
	if x != nil {
		return x.UptimeValid
	}
	return false
}

func (x *QualityExporterState) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

func (x *QualityExporterState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *QualityExporterState) GetSamplingEpoch() uint64 {
	if x != nil {
		return x.SamplingEpoch
	}
	return 0
}

func (x *QualityExporterState) GetSamplingRate() uint64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *QualityExporterState) GetSamplingRateKnown() bool {
	if x != nil {
		return x.SamplingRateKnown
	}
	return false
}

func (x *QualityExporterState) GetWindows() *QualityWindows {
	if x != nil {
		return x.Windows
	}
	return nil
}

type QualitySourceState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Exporter         *QualityExporterKey    `protobuf:"bytes,1,opt,name=exporter,proto3" json:"exporter,omitempty"`
	SourceIdType     uint32                 `protobuf:"varint,2,opt,name=source_id_type,json=sourceIdType,proto3" json:"source_id_type,omitempty"`
	SourceIdValue    uint32                 `protobuf:"varint,3,opt,name=source_id_value,json=sourceIdValue,proto3" json:"source_id_value,omitempty"`
	Initialized      bool                   `protobuf:"varint,4,opt,name=initialized,proto3" json:"initialized,omitempty"`
	ExpectedSequence uint32                 `protobuf:"varint,5,opt,name=expected_sequence,json=expectedSequence,proto3" json:"expected_sequence,omitempty"`
	SamplePool       uint32                 `protobuf:"varint,6,opt,name=sample_pool,json=samplePool,proto3" json:"sample_pool,omitempty"`
	Drops            uint32                 `protobuf:"varint,7,opt,name=drops,proto3" json:"drops,omitempty"`
	SamplingRate     uint64                 `protobuf:"varint,8,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`
	RateKnown        bool                   `protobuf:"varint,9,opt,name=rate_known,json=rateKnown,proto3" json:"rate_known,omitempty"`
	LastSeenUnixMs   int64                  `protobuf:"varint,10,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	ExporterEpoch    uint64                 `protobuf:"varint,11,opt,name=exporter_epoch,json=exporterEpoch,proto3" json:"exporter_epoch,omitempty"`
	Epoch            uint64                 `protobuf:"varint,12,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Windows          *QualityWindows        `protobuf:"bytes,13,opt,name=windows,proto3" json:"windows,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QualitySourceState) Reset() {
	*x = QualitySourceState{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualitySourceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualitySourceState) ProtoMessage() {}

func (x *QualitySourceState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualitySourceState.ProtoReflect.Descriptor instead.
func (*QualitySourceState) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{8}
}

func (x *QualitySourceState) GetExporter() *QualityExporterKey {
	if x != nil {
		return x.Exporter
	}
	return nil
}

func (x *QualitySourceState) GetSourceIdType() uint32 {
	if x != nil {
		return x.SourceIdType
	}
	return 0
}

func (x *QualitySourceState) GetSourceIdValue() uint32 {
	if x != nil {
		return x.SourceIdValue
	}
	return 0
}

func (x *QualitySourceState) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *QualitySourceState) GetExpectedSequence() uint32 {
	if x != nil {
		return x.ExpectedSequence
	}
	return 0
}

func (x *QualitySourceState) GetSamplePool() uint32 {
	if x != nil {
		return x.SamplePool
	}
	return 0
}

func (x *QualitySourceState) GetDrops() uint32 {
	if x != nil {
		return x.Drops
	}
	return 0
}

func (x *QualitySourceState) GetSamplingRate() uint64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *QualitySourceState) GetRateKnown() bool {
	if x != nil {
		return x.RateKnown
	}
	return false
}

func (x *QualitySourceState) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

func (x *QualitySourceState) GetExporterEpoch() uint64 {
	if x != nil {
		return x.ExporterEpoch
	}
	return 0
}

func (x *QualitySourceState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *QualitySourceState) GetWindows() *QualityWindows {
	if x != nil {
		return x.Windows
	}
	return nil
}

type QualityDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatagramId    []byte                 `protobuf:"bytes,1,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	ExporterEpoch uint64                 `protobuf:"varint,2,opt,name=exporter_epoch,json=exporterEpoch,proto3" json:"exporter_epoch,omitempty"`
	RecordFlags   []uint64               `protobuf:"varint,3,rep,packed,name=record_flags,json=recordFlags,proto3" json:"record_flags,omitempty"`
	RecordEpochs  []uint64               `protobuf:"varint,4,rep,packed,name=record_epochs,json=recordEpochs,proto3" json:"record_epochs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityDecision) Reset() {
	*x = QualityDecision{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityDecision) ProtoMessage() {}

func (x *QualityDecision) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityDecision.ProtoReflect.Descriptor instead.
func (*QualityDecision) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{9}
}

func (x *QualityDecision) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *QualityDecision) GetExporterEpoch() uint64 {
	if x != nil {
		return x.ExporterEpoch
	}
	return 0
}

func (x *QualityDecision) GetRecordFlags() []uint64 {
	if x != nil {
		return x.RecordFlags
	}
	return nil
}

func (x *QualityDecision) GetRecordEpochs() []uint64 {
	if x != nil {
		return x.RecordEpochs
	}
	return nil
}

type QualityJournalRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StateSchemaVersion uint32                 `protobuf:"varint,1,opt,name=state_schema_version,json=stateSchemaVersion,proto3" json:"state_schema_version,omitempty"`
	DatagramId         []byte                 `protobuf:"bytes,2,opt,name=datagram_id,json=datagramId,proto3" json:"datagram_id,omitempty"`
	WalSegment         uint64                 `protobuf:"varint,3,opt,name=wal_segment,json=walSegment,proto3" json:"wal_segment,omitempty"`
	WalOffset          int64                  `protobuf:"varint,4,opt,name=wal_offset,json=walOffset,proto3" json:"wal_offset,omitempty"`
	ExporterState      *QualityExporterState  `protobuf:"bytes,5,opt,name=exporter_state,json=exporterState,proto3" json:"exporter_state,omitempty"`
	SourceStates       []*QualitySourceState  `protobuf:"bytes,6,rep,name=source_states,json=sourceStates,proto3" json:"source_states,omitempty"`
	Decision           *QualityDecision       `protobuf:"bytes,7,opt,name=decision,proto3" json:"decision,omitempty"`
	PayloadSha256      []byte                 `protobuf:"bytes,8,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	CollectorId        string                 `protobuf:"bytes,9,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QualityJournalRecord) Reset() {
	*x = QualityJournalRecord{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityJournalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityJournalRecord) ProtoMessage() {}

func (x *QualityJournalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityJournalRecord.ProtoReflect.Descriptor instead.
func (*QualityJournalRecord) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{10}
}

func (x *QualityJournalRecord) GetStateSchemaVersion() uint32 {
	if x != nil {
		return x.StateSchemaVersion
	}
	return 0
}

func (x *QualityJournalRecord) GetDatagramId() []byte {
	if x != nil {
		return x.DatagramId
	}
	return nil
}

func (x *QualityJournalRecord) GetWalSegment() uint64 {
	if x != nil {
		return x.WalSegment
	}
	return 0
}

func (x *QualityJournalRecord) GetWalOffset() int64 {
	if x != nil {
		return x.WalOffset
	}
	return 0
}

func (x *QualityJournalRecord) GetExporterState() *QualityExporterState {
	if x != nil {
		return x.ExporterState
	}
	return nil
}

func (x *QualityJournalRecord) GetSourceStates() []*QualitySourceState {
	if x != nil {
		return x.SourceStates
	}
	return nil
}

func (x *QualityJournalRecord) GetDecision() *QualityDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *QualityJournalRecord) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

func (x *QualityJournalRecord) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type QualityStateSnapshot struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	StateSchemaVersion uint32                  `protobuf:"varint,1,opt,name=state_schema_version,json=stateSchemaVersion,proto3" json:"state_schema_version,omitempty"`
	CollectorId        string                  `protobuf:"bytes,2,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	CreatedAtUnixMs    int64                   `protobuf:"varint,3,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	Exporters          []*QualityExporterState `protobuf:"bytes,4,rep,name=exporters,proto3" json:"exporters,omitempty"`
	Sources            []*QualitySourceState   `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	PendingDecisions   []*QualityDecision      `protobuf:"bytes,6,rep,name=pending_decisions,json=pendingDecisions,proto3" json:"pending_decisions,omitempty"`
	PayloadSha256      []byte                  `protobuf:"bytes,7,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QualityStateSnapshot) Reset() {
	*x = QualityStateSnapshot{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityStateSnapshot) ProtoMessage() {}

func (x *QualityStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityStateSnapshot.ProtoReflect.Descriptor instead.
func (*QualityStateSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{11}
}

func (x *QualityStateSnapshot) GetStateSchemaVersion() uint32 {
	if x != nil {
		return x.StateSchemaVersion
	}
	return 0
}

func (x *QualityStateSnapshot) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *QualityStateSnapshot) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *QualityStateSnapshot) GetExporters() []*QualityExporterState {
	if x != nil {
		return x.Exporters
	}
	return nil
}

func (x *QualityStateSnapshot) GetSources() []*QualitySourceState {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *QualityStateSnapshot) GetPendingDecisions() []*QualityDecision {
	if x != nil {
		return x.PendingDecisions
	}
	return nil
}

func (x *QualityStateSnapshot) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

// QualityCheckpoint contains only terminally committed post-state for one
// exporter quality identity. It is safe for a new collector owner to restore
// from a typed keyspace in the compacted collect-state topic; state_key is the
// 32-byte owner-fenced portion of that Kafka key.
type QualityCheckpoint struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CheckpointSchemaVersion uint32                 `protobuf:"varint,1,opt,name=checkpoint_schema_version,json=checkpointSchemaVersion,proto3" json:"checkpoint_schema_version,omitempty"`
	StateKey                []byte                 `protobuf:"bytes,2,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	StateIdentityKey        []byte                 `protobuf:"bytes,3,opt,name=state_identity_key,json=stateIdentityKey,proto3" json:"state_identity_key,omitempty"`
	TenantId                string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectorId             string                 `protobuf:"bytes,5,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ExporterId              string                 `protobuf:"bytes,6,opt,name=exporter_id,json=exporterId,proto3" json:"exporter_id,omitempty"`
	RegistryVersion         uint64                 `protobuf:"varint,7,opt,name=registry_version,json=registryVersion,proto3" json:"registry_version,omitempty"`
	OwnershipEpoch          uint64                 `protobuf:"varint,8,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	StateGeneration         uint64                 `protobuf:"varint,9,opt,name=state_generation,json=stateGeneration,proto3" json:"state_generation,omitempty"`
	CommittedAtUnixMs       int64                  `protobuf:"varint,10,opt,name=committed_at_unix_ms,json=committedAtUnixMs,proto3" json:"committed_at_unix_ms,omitempty"`
	ObservationDomainId     uint64                 `protobuf:"varint,11,opt,name=observation_domain_id,json=observationDomainId,proto3" json:"observation_domain_id,omitempty"`
	ExporterState           *QualityExporterState  `protobuf:"bytes,12,opt,name=exporter_state,json=exporterState,proto3" json:"exporter_state,omitempty"`
	SourceStates            []*QualitySourceState  `protobuf:"bytes,13,rep,name=source_states,json=sourceStates,proto3" json:"source_states,omitempty"`
	PayloadSha256           []byte                 `protobuf:"bytes,14,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *QualityCheckpoint) Reset() {
	*x = QualityCheckpoint{}
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityCheckpoint) ProtoMessage() {}

func (x *QualityCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_flowcollect_flowpb_normalized_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityCheckpoint.ProtoReflect.Descriptor instead.
func (*QualityCheckpoint) Descriptor() ([]byte, []int) {
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP(), []int{12}
}

func (x *QualityCheckpoint) GetCheckpointSchemaVersion() uint32 {
	if x != nil {
		return x.CheckpointSchemaVersion
	}
	return 0
}

func (x *QualityCheckpoint) GetStateKey() []byte {
	if x != nil {
		return x.StateKey
	}
	return nil
}

func (x *QualityCheckpoint) GetStateIdentityKey() []byte {
	if x != nil {
		return x.StateIdentityKey
	}
	return nil
}

func (x *QualityCheckpoint) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QualityCheckpoint) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *QualityCheckpoint) GetExporterId() string {
	if x != nil {
		return x.ExporterId
	}
	return ""
}

func (x *QualityCheckpoint) GetRegistryVersion() uint64 {
	if x != nil {
		return x.RegistryVersion
	}
	return 0
}

func (x *QualityCheckpoint) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *QualityCheckpoint) GetStateGeneration() uint64 {
	if x != nil {
		return x.StateGeneration
	}
	return 0
}

func (x *QualityCheckpoint) GetCommittedAtUnixMs() int64 {
	if x != nil {
		return x.CommittedAtUnixMs
	}
	return 0
}

func (x *QualityCheckpoint) GetObservationDomainId() uint64 {
	if x != nil {
		return x.ObservationDomainId
	}
	return 0
}

func (x *QualityCheckpoint) GetExporterState() *QualityExporterState {
	if x != nil {
		return x.ExporterState
	}
	return nil
}

func (x *QualityCheckpoint) GetSourceStates() []*QualitySourceState {
	if x != nil {
		return x.SourceStates
	}
	return nil
}

func (x *QualityCheckpoint) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

var File_internal_flowcollect_flowpb_normalized_proto protoreflect.FileDescriptor

const file_internal_flowcollect_flowpb_normalized_proto_rawDesc = "" +
	"\n" +
	",internal/flowcollect/flowpb/normalized.proto\x12\x10watchdog.flow.v1\"\xcc\x06\n" +
	"\x15NormalizedRecordBatch\x120\n" +
	"\x14batch_schema_version\x18\x01 \x01(\rR\x12batchSchemaVersion\x12.\n" +
	"\x13normalized_batch_id\x18\x02 \x01(\fR\x11normalizedBatchId\x12\x1f\n" +
	"\vdatagram_id\x18\x03 \x01(\fR\n" +
	"datagramId\x12#\n" +
	"\rvirtual_shard\x18\x04 \x01(\rR\fvirtualShard\x122\n" +
	"\x15partition_map_version\x18\x05 \x01(\rR\x13partitionMapVersion\x12-\n" +
	"\x12physical_partition\x18\x06 \x01(\rR\x11physicalPartition\x12+\n" +
	"\x11replay_generation\x18\a \x01(\rR\x10replayGeneration\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12!\n" +
	"\fcollector_id\x18\t \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vexporter_id\x18\n" +
	" \x01(\tR\n" +
	"exporterId\x12)\n" +
	"\x10registry_version\x18\v \x01(\x04R\x0fregistryVersion\x12-\n" +
	"\x13received_at_unix_ms\x18\f \x01(\x03R\x10receivedAtUnixMs\x12\x1a\n" +
	"\bprotocol\x18\r \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x0e \x01(\fR\bsourceIp\x122\n" +
	"\x15observation_domain_id\x18\x0f \x01(\x04R\x13observationDomainId\x12<\n" +
	"\arecords\x18\x10 \x03(\v2\".watchdog.flow.v1.NormalizedRecordR\arecords\x12 \n" +
	"\fsub_agent_id\x18  \x01(\rR\n" +
	"subAgentId\x12+\n" +
	"\x11datagram_sequence\x18! \x01(\rR\x10datagramSequence\x12\x19\n" +
	"\bagent_ip\x18\" \x01(\fR\aagentIp\x12%\n" +
	"\x0eexporter_epoch\x18# \x01(\x04R\rexporterEpochJ\x04\b\x11\x10 \"\xb3\b\n" +
	"\x10NormalizedRecord\x12!\n" +
	"\frecord_index\x18\x01 \x01(\rR\vrecordIndex\x12+\n" +
	"\x12event_time_unix_ms\x18\x02 \x01(\x03R\x0feventTimeUnixMs\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x120\n" +
	"\x14observation_if_index\x18\x05 \x01(\rR\x12observationIfIndex\x123\n" +
	"\x15observation_direction\x18\x06 \x01(\rR\x14observationDirection\x12\x13\n" +
	"\x05in_if\x18\a \x01(\rR\x04inIf\x12\x15\n" +
	"\x06out_if\x18\b \x01(\rR\x05outIf\x12\x15\n" +
	"\x06src_ip\x18\t \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\n" +
	" \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\v \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\f \x01(\rR\adstPort\x12\x19\n" +
	"\bip_proto\x18\r \x01(\rR\aipProto\x12\x1b\n" +
	"\ttcp_flags\x18\x0e \x01(\rR\btcpFlags\x12\x1b\n" +
	"\traw_bytes\x18\x0f \x01(\x04R\brawBytes\x12\x1f\n" +
	"\vraw_packets\x18\x10 \x01(\x04R\n" +
	"rawPackets\x12#\n" +
	"\rsampling_mode\x18\x11 \x01(\rR\fsamplingMode\x12#\n" +
	"\rsampling_rate\x18\x12 \x01(\x04R\fsamplingRate\x12'\n" +
	"\x0festimated_bytes\x18\x13 \x01(\x04R\x0eestimatedBytes\x12+\n" +
	"\x11estimated_packets\x18\x14 \x01(\x04R\x10estimatedPackets\x12(\n" +
	"\x10flow_duration_ms\x18\x15 \x01(\x04R\x0eflowDurationMs\x12#\n" +
	"\rquality_flags\x18\x16 \x01(\x04R\fqualityFlags\x12\x15\n" +
	"\x06src_as\x18  \x01(\rR\x05srcAs\x12\x15\n" +
	"\x06dst_as\x18! \x01(\rR\x05dstAs\x12$\n" +
	"\x0esource_id_type\x18\" \x01(\rR\fsourceIdType\x12&\n" +
	"\x0fsource_id_value\x18# \x01(\rR\rsourceIdValue\x12'\n" +
	"\x0fsample_sequence\x18$ \x01(\rR\x0esampleSequence\x12\x1f\n" +
	"\vsample_pool\x18% \x01(\x04R\n" +
	"samplePool\x12%\n" +
	"\x0eexporter_drops\x18& \x01(\x04R\rexporterDrops\x12!\n" +
	"\fsample_index\x18' \x01(\rR\vsampleIndex\x12#\n" +
	"\rquality_epoch\x18( \x01(\x04R\fqualityEpochJ\x04\b\x17\x10 \"\xc1\x05\n" +
	"\fCollectState\x120\n" +
	"\x14state_schema_version\x18\x01 \x01(\rR\x12stateSchemaVersion\x12\x19\n" +
	"\bstate_id\x18\x02 \x01(\fR\astateId\x12\x1b\n" +
	"\tstate_key\x18\x03 \x01(\fR\bstateKey\x12\x1f\n" +
	"\vdatagram_id\x18\x04 \x01(\fR\n" +
	"datagramId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12!\n" +
	"\fcollector_id\x18\x06 \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vexporter_id\x18\a \x01(\tR\n" +
	"exporterId\x12)\n" +
	"\x10registry_version\x18\b \x01(\x04R\x0fregistryVersion\x12-\n" +
	"\x13received_at_unix_ms\x18\t \x01(\x03R\x10receivedAtUnixMs\x12\x1a\n" +
	"\bprotocol\x18\n" +
	" \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\v \x01(\fR\bsourceIp\x122\n" +
	"\x15observation_domain_id\x18\f \x01(\x04R\x13observationDomainId\x12%\n" +
	"\x0etemplates_json\x18\r \x01(\fR\rtemplatesJson\x12.\n" +
	"\x13sampling_rates_json\x18\x0e \x01(\fR\x11samplingRatesJson\x12%\n" +
	"\x0epayload_sha256\x18\x0f \x01(\fR\rpayloadSha256\x12,\n" +
	"\x12state_identity_key\x18\x10 \x01(\fR\x10stateIdentityKey\x12'\n" +
	"\x0fownership_epoch\x18\x11 \x01(\x04R\x0eownershipEpoch\x12)\n" +
	"\x10state_generation\x18\x12 \x01(\x04R\x0fstateGeneration\"\xf7\x04\n" +
	"\rDecodeFailure\x124\n" +
	"\x16failure_schema_version\x18\x01 \x01(\rR\x14failureSchemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\fR\aeventId\x12\x1f\n" +
	"\vdatagram_id\x18\x03 \x01(\fR\n" +
	"datagramId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12!\n" +
	"\fcollector_id\x18\x05 \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vexporter_id\x18\x06 \x01(\tR\n" +
	"exporterId\x12)\n" +
	"\x10registry_version\x18\a \x01(\x04R\x0fregistryVersion\x12-\n" +
	"\x13received_at_unix_ms\x18\b \x01(\x03R\x10receivedAtUnixMs\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\n" +
	" \x01(\fR\bsourceIp\x122\n" +
	"\x15observation_domain_id\x18\v \x01(\x04R\x13observationDomainId\x12\x1d\n" +
	"\n" +
	"error_code\x18\f \x01(\tR\terrorCode\x12#\n" +
	"\rerror_summary\x18\r \x01(\tR\ferrorSummary\x12\x1a\n" +
	"\battempts\x18\x0e \x01(\rR\battempts\x12%\n" +
	"\x0epayload_sha256\x18\x0f \x01(\fR\rpayloadSha256\x12\x18\n" +
	"\apayload\x18\x10 \x01(\fR\apayload\x12+\n" +
	"\x11payload_truncated\x18\x11 \x01(\bR\x10payloadTruncated\"\x8a\x03\n" +
	"\x0fQuarantineEvent\x120\n" +
	"\x14event_schema_version\x18\x01 \x01(\rR\x12eventSchemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\fR\aeventId\x12!\n" +
	"\fcollector_id\x18\x03 \x01(\tR\vcollectorId\x12-\n" +
	"\x13received_at_unix_ms\x18\x04 \x01(\x03R\x10receivedAtUnixMs\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x06 \x01(\fR\bsourceIp\x122\n" +
	"\x15observation_domain_id\x18\a \x01(\x04R\x13observationDomainId\x12\x1f\n" +
	"\vreason_code\x18\b \x01(\tR\n" +
	"reasonCode\x12#\n" +
	"\rpayload_bytes\x18\t \x01(\rR\fpayloadBytes\x12%\n" +
	"\x0epayload_sha256\x18\n" +
	" \x01(\fR\rpayloadSha256\"\xb1\x01\n" +
	"\x12QualityExporterKey\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\fR\bsourceIp\x12%\n" +
	"\x0esequence_scope\x18\x03 \x01(\x04R\rsequenceScope\x12\x19\n" +
	"\bagent_ip\x18\x04 \x01(\fR\aagentIp\x12 \n" +
	"\fsub_agent_id\x18\x05 \x01(\rR\n" +
	"subAgentId\"\xd0\x02\n" +
	"\x0eQualityWindows\x123\n" +
	"\x16template_until_unix_ms\x18\x01 \x01(\x03R\x13templateUntilUnixMs\x12)\n" +
	"\x11gap_until_unix_ms\x18\x02 \x01(\x03R\x0egapUntilUnixMs\x126\n" +
	"\x18pool_reset_until_unix_ms\x18\x03 \x01(\x03R\x14poolResetUntilUnixMs\x128\n" +
	"\x19rate_change_until_unix_ms\x18\x04 \x01(\x03R\x15rateChangeUntilUnixMs\x121\n" +
	"\x15restart_until_unix_ms\x18\x05 \x01(\x03R\x12restartUntilUnixMs\x129\n" +
	"\x1aout_of_order_until_unix_ms\x18\x06 \x01(\x03R\x15outOfOrderUntilUnixMs\"\xd1\x03\n" +
	"\x14QualityExporterState\x126\n" +
	"\x03key\x18\x01 \x01(\v2$.watchdog.flow.v1.QualityExporterKeyR\x03key\x12 \n" +
	"\vinitialized\x18\x02 \x01(\bR\vinitialized\x12+\n" +
	"\x11expected_sequence\x18\x03 \x01(\rR\x10expectedSequence\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\rR\x06uptime\x12!\n" +
	"\fuptime_valid\x18\x05 \x01(\bR\vuptimeValid\x12)\n" +
	"\x11last_seen_unix_ms\x18\x06 \x01(\x03R\x0elastSeenUnixMs\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x04R\x05epoch\x12%\n" +
	"\x0esampling_epoch\x18\b \x01(\x04R\rsamplingEpoch\x12#\n" +
	"\rsampling_rate\x18\t \x01(\x04R\fsamplingRate\x12.\n" +
	"\x13sampling_rate_known\x18\n" +
	" \x01(\bR\x11samplingRateKnown\x12:\n" +
	"\awindows\x18\v \x01(\v2 .watchdog.flow.v1.QualityWindowsR\awindows\"\x92\x04\n" +
	"\x12QualitySourceState\x12@\n" +
	"\bexporter\x18\x01 \x01(\v2$.watchdog.flow.v1.QualityExporterKeyR\bexporter\x12$\n" +
	"\x0esource_id_type\x18\x02 \x01(\rR\fsourceIdType\x12&\n" +
	"\x0fsource_id_value\x18\x03 \x01(\rR\rsourceIdValue\x12 \n" +
	"\vinitialized\x18\x04 \x01(\bR\vinitialized\x12+\n" +
	"\x11expected_sequence\x18\x05 \x01(\rR\x10expectedSequence\x12\x1f\n" +
	"\vsample_pool\x18\x06 \x01(\rR\n" +
	"samplePool\x12\x14\n" +
	"\x05drops\x18\a \x01(\rR\x05drops\x12#\n" +
	"\rsampling_rate\x18\b \x01(\x04R\fsamplingRate\x12\x1d\n" +
	"\n" +
	"rate_known\x18\t \x01(\bR\trateKnown\x12)\n" +
	"\x11last_seen_unix_ms\x18\n" +
	" \x01(\x03R\x0elastSeenUnixMs\x12%\n" +
	"\x0eexporter_epoch\x18\v \x01(\x04R\rexporterEpoch\x12\x14\n" +
	"\x05epoch\x18\f \x01(\x04R\x05epoch\x12:\n" +
	"\awindows\x18\r \x01(\v2 .watchdog.flow.v1.QualityWindowsR\awindows\"\xa1\x01\n" +
	"\x0fQualityDecision\x12\x1f\n" +
	"\vdatagram_id\x18\x01 \x01(\fR\n" +
	"datagramId\x12%\n" +
	"\x0eexporter_epoch\x18\x02 \x01(\x04R\rexporterEpoch\x12!\n" +
	"\frecord_flags\x18\x03 \x03(\x04R\vrecordFlags\x12#\n" +
	"\rrecord_epochs\x18\x04 \x03(\x04R\frecordEpochs\"\xcc\x03\n" +
	"\x14QualityJournalRecord\x120\n" +
	"\x14state_schema_version\x18\x01 \x01(\rR\x12stateSchemaVersion\x12\x1f\n" +
	"\vdatagram_id\x18\x02 \x01(\fR\n" +
	"datagramId\x12\x1f\n" +
	"\vwal_segment\x18\x03 \x01(\x04R\n" +
	"walSegment\x12\x1d\n" +
	"\n" +
	"wal_offset\x18\x04 \x01(\x03R\twalOffset\x12M\n" +
	"\x0eexporter_state\x18\x05 \x01(\v2&.watchdog.flow.v1.QualityExporterStateR\rexporterState\x12I\n" +
	"\rsource_states\x18\x06 \x03(\v2$.watchdog.flow.v1.QualitySourceStateR\fsourceStates\x12=\n" +
	"\bdecision\x18\a \x01(\v2!.watchdog.flow.v1.QualityDecisionR\bdecision\x12%\n" +
	"\x0epayload_sha256\x18\b \x01(\fR\rpayloadSha256\x12!\n" +
	"\fcollector_id\x18\t \x01(\tR\vcollectorId\"\x95\x03\n" +
	"\x14QualityStateSnapshot\x120\n" +
	"\x14state_schema_version\x18\x01 \x01(\rR\x12stateSchemaVersion\x12!\n" +
	"\fcollector_id\x18\x02 \x01(\tR\vcollectorId\x12+\n" +
	"\x12created_at_unix_ms\x18\x03 \x01(\x03R\x0fcreatedAtUnixMs\x12D\n" +
	"\texporters\x18\x04 \x03(\v2&.watchdog.flow.v1.QualityExporterStateR\texporters\x12>\n" +
	"\asources\x18\x05 \x03(\v2$.watchdog.flow.v1.QualitySourceStateR\asources\x12N\n" +
	"\x11pending_decisions\x18\x06 \x03(\v2!.watchdog.flow.v1.QualityDecisionR\x10pendingDecisions\x12%\n" +
	"\x0epayload_sha256\x18\a \x01(\fR\rpayloadSha256\"\xa0\x05\n" +
	"\x11QualityCheckpoint\x12:\n" +
	"\x19checkpoint_schema_version\x18\x01 \x01(\rR\x17checkpointSchemaVersion\x12\x1b\n" +
	"\tstate_key\x18\x02 \x01(\fR\bstateKey\x12,\n" +
	"\x12state_identity_key\x18\x03 \x01(\fR\x10stateIdentityKey\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12!\n" +
	"\fcollector_id\x18\x05 \x01(\tR\vcollectorId\x12\x1f\n" +
	"\vexporter_id\x18\x06 \x01(\tR\n" +
	"exporterId\x12)\n" +
	"\x10registry_version\x18\a \x01(\x04R\x0fregistryVersion\x12'\n" +
	"\x0fownership_epoch\x18\b \x01(\x04R\x0eownershipEpoch\x12)\n" +
	"\x10state_generation\x18\t \x01(\x04R\x0fstateGeneration\x12/\n" +
	"\x14committed_at_unix_ms\x18\n" +
	" \x01(\x03R\x11committedAtUnixMs\x122\n" +
	"\x15observation_domain_id\x18\v \x01(\x04R\x13observationDomainId\x12M\n" +
	"\x0eexporter_state\x18\f \x01(\v2&.watchdog.flow.v1.QualityExporterStateR\rexporterState\x12I\n" +
	"\rsource_states\x18\r \x03(\v2$.watchdog.flow.v1.QualitySourceStateR\fsourceStates\x12%\n" +
	"\x0epayload_sha256\x18\x0e \x01(\fR\rpayloadSha256BCZAgithub.com/cloudcache/watchdog/internal/flowcollect/flowpb;flowpbb\x06proto3"

var (
	file_internal_flowcollect_flowpb_normalized_proto_rawDescOnce sync.Once
	file_internal_flowcollect_flowpb_normalized_proto_rawDescData []byte
)

func file_internal_flowcollect_flowpb_normalized_proto_rawDescGZIP() []byte {
	file_internal_flowcollect_flowpb_normalized_proto_rawDescOnce.Do(func() {
		file_internal_flowcollect_flowpb_normalized_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_flowcollect_flowpb_normalized_proto_rawDesc), len(file_internal_flowcollect_flowpb_normalized_proto_rawDesc)))
	})
	return file_internal_flowcollect_flowpb_normalized_proto_rawDescData
}

var file_internal_flowcollect_flowpb_normalized_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_flowcollect_flowpb_normalized_proto_goTypes = []any{
	(*NormalizedRecordBatch)(nil), // 0: watchdog.flow.v1.NormalizedRecordBatch
	(*NormalizedRecord)(nil),      // 1: watchdog.flow.v1.NormalizedRecord
	(*CollectState)(nil),          // 2: watchdog.flow.v1.CollectState
	(*DecodeFailure)(nil),         // 3: watchdog.flow.v1.DecodeFailure
	(*QuarantineEvent)(nil),       // 4: watchdog.flow.v1.QuarantineEvent
	(*QualityExporterKey)(nil),    // 5: watchdog.flow.v1.QualityExporterKey
	(*QualityWindows)(nil),        // 6: watchdog.flow.v1.QualityWindows
	(*QualityExporterState)(nil),  // 7: watchdog.flow.v1.QualityExporterState
	(*QualitySourceState)(nil),    // 8: watchdog.flow.v1.QualitySourceState
	(*QualityDecision)(nil),       // 9: watchdog.flow.v1.QualityDecision
	(*QualityJournalRecord)(nil),  // 10: watchdog.flow.v1.QualityJournalRecord
	(*QualityStateSnapshot)(nil),  // 11: watchdog.flow.v1.QualityStateSnapshot
	(*QualityCheckpoint)(nil),     // 12: watchdog.flow.v1.QualityCheckpoint
}
var file_internal_flowcollect_flowpb_normalized_proto_depIdxs = []int32{
	1,  // 0: watchdog.flow.v1.NormalizedRecordBatch.records:type_name -> watchdog.flow.v1.NormalizedRecord
	5,  // 1: watchdog.flow.v1.QualityExporterState.key:type_name -> watchdog.flow.v1.QualityExporterKey
	6,  // 2: watchdog.flow.v1.QualityExporterState.windows:type_name -> watchdog.flow.v1.QualityWindows
	5,  // 3: watchdog.flow.v1.QualitySourceState.exporter:type_name -> watchdog.flow.v1.QualityExporterKey
	6,  // 4: watchdog.flow.v1.QualitySourceState.windows:type_name -> watchdog.flow.v1.QualityWindows
	7,  // 5: watchdog.flow.v1.QualityJournalRecord.exporter_state:type_name -> watchdog.flow.v1.QualityExporterState
	8,  // 6: watchdog.flow.v1.QualityJournalRecord.source_states:type_name -> watchdog.flow.v1.QualitySourceState
	9,  // 7: watchdog.flow.v1.QualityJournalRecord.decision:type_name -> watchdog.flow.v1.QualityDecision
	7,  // 8: watchdog.flow.v1.QualityStateSnapshot.exporters:type_name -> watchdog.flow.v1.QualityExporterState
	8,  // 9: watchdog.flow.v1.QualityStateSnapshot.sources:type_name -> watchdog.flow.v1.QualitySourceState
	9,  // 10: watchdog.flow.v1.QualityStateSnapshot.pending_decisions:type_name -> watchdog.flow.v1.QualityDecision
	7,  // 11: watchdog.flow.v1.QualityCheckpoint.exporter_state:type_name -> watchdog.flow.v1.QualityExporterState
	8,  // 12: watchdog.flow.v1.QualityCheckpoint.source_states:type_name -> watchdog.flow.v1.QualitySourceState
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_flowcollect_flowpb_normalized_proto_init() }
func file_internal_flowcollect_flowpb_normalized_proto_init() {
	if File_internal_flowcollect_flowpb_normalized_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_flowcollect_flowpb_normalized_proto_rawDesc), len(file_internal_flowcollect_flowpb_normalized_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_flowcollect_flowpb_normalized_proto_goTypes,
		DependencyIndexes: file_internal_flowcollect_flowpb_normalized_proto_depIdxs,
		MessageInfos:      file_internal_flowcollect_flowpb_normalized_proto_msgTypes,
	}.Build()
	File_internal_flowcollect_flowpb_normalized_proto = out.File
	file_internal_flowcollect_flowpb_normalized_proto_goTypes = nil
	file_internal_flowcollect_flowpb_normalized_proto_depIdxs = nil
}
