// SPDX-FileCopyrightText: 2026 Watchdog contributors
// SPDX-License-Identifier: AGPL-3.0-only

package server

import (
	"context"
	"database/sql"
	"encoding/json"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/cloudcache/watchdog/internal/flowvpn"
	"github.com/gin-gonic/gin"
)

// Findings read/triage API (KISS-06 VPN Tier-1): the consumer surface over the
// materialized flow_vpn_findings — list/get for review, plus the disposition
// action for triage. Findings are generated by the scoring pipeline, never
// created through the API; only their disposition is mutable here.

const (
	vpnDispositionUnreviewed    = "unreviewed"
	vpnDispositionConfirmed     = "confirmed"
	vpnDispositionFalsePositive = "false_positive"
	vpnDispositionAllowed       = "allowed"
	vpnDispositionSuppressed    = "suppressed"

	maxVPNFindingNoteBytes = 2000
)

func validVPNDisposition(value string) bool {
	switch value {
	case vpnDispositionUnreviewed, vpnDispositionConfirmed, vpnDispositionFalsePositive, vpnDispositionAllowed, vpnDispositionSuppressed:
		return true
	}
	return false
}

type vpnFindingDTO struct {
	ID                 string                   `json:"id"`
	WindowStart        time.Time                `json:"window_start"`
	WindowEnd          time.Time                `json:"window_end"`
	ConversationKey    string                   `json:"conversation_key"`
	LocalIP            string                   `json:"local_ip"`
	RemoteIP           string                   `json:"remote_ip"`
	PrimaryProtocol    uint8                    `json:"primary_protocol"`
	PrimaryLocalPort   uint16                   `json:"primary_local_port"`
	PrimaryRemotePort  uint16                   `json:"primary_remote_port"`
	LocalToRemoteBytes uint64                   `json:"local_to_remote_bytes"`
	RemoteToLocalBytes uint64                   `json:"remote_to_local_bytes"`
	FlowRecordCount    uint64                   `json:"flow_record_count"`
	ActiveBucketCount  uint32                   `json:"active_bucket_count"`
	MaxDurationMS      uint64                   `json:"max_duration_ms"`
	PacketBytesP50     uint64                   `json:"packet_bytes_p50"`
	RemoteASN          uint32                   `json:"remote_asn"`
	RemoteCountry      string                   `json:"remote_country"`
	RemotePrefixID     string                   `json:"remote_prefix_id"`
	LocalPrefixID      string                   `json:"local_prefix_id"`
	CompleteRatio      float64                  `json:"complete_ratio"`
	Score              uint16                   `json:"score"`
	RiskLevel          string                   `json:"risk_level"`
	Verdict            string                   `json:"verdict"`
	SymmetryRatio      float64                  `json:"symmetry_ratio"`
	DominanceRatio     float64                  `json:"dominance_ratio"`
	ProbeRecommended   bool                     `json:"probe_recommended"`
	ProbeBlockReason   string                   `json:"probe_block_reason"`
	DecisionRuleID     string                   `json:"decision_rule_id"`
	RuleSetVersion     string                   `json:"rule_set_version"`
	FamilyHints        []flowvpn.ProtocolFamily `json:"family_hints,omitempty"`
	Evidence           json.RawMessage          `json:"evidence"`
	SourceGeneration   uint64                   `json:"source_generation"`
	GeneratedAt        time.Time                `json:"generated_at"`
	Disposition        string                   `json:"disposition"`
	DispositionNote    string                   `json:"disposition_note"`
	DispositionBy      string                   `json:"disposition_by,omitempty"`
	DispositionAt      *time.Time               `json:"disposition_at,omitempty"`
	ProbeStatus        string                   `json:"probe_status"`
	ProbeJobID         string                   `json:"probe_job_id,omitempty"`
	ProbeResult        json.RawMessage          `json:"probe_result,omitempty"`
	RowVersion         uint64                   `json:"row_version"`
	CreatedAt          time.Time                `json:"created_at"`
	UpdatedAt          time.Time                `json:"updated_at"`
}

const vpnFindingSelect = `SELECT id, window_start, window_end, conversation_key, local_ip, remote_ip,
	primary_protocol, primary_local_port, primary_remote_port, local_to_remote_bytes, remote_to_local_bytes,
	flow_record_count, active_bucket_count, max_duration_ms, packet_bytes_p50, remote_asn, remote_country,
	remote_prefix_id, local_prefix_id, complete_ratio, score, risk_level, verdict, symmetry_ratio, dominance_ratio,
	probe_recommended, probe_block_reason, decision_rule_id, rule_set_version, family_hints, evidence_json,
	source_generation, generated_at, disposition, disposition_note, disposition_by, disposition_at,
	probe_status, probe_job_id, probe_result_json, row_version, created_at, updated_at FROM flow_vpn_findings`

func scanVPNFinding(row rowScanner) (vpnFindingDTO, error) {
	var dto vpnFindingDTO
	var familyHints, probeResult []byte
	var dispositionBy, probeJobID sql.NullString
	var dispositionAt sql.NullTime
	if err := row.Scan(&dto.ID, &dto.WindowStart, &dto.WindowEnd, &dto.ConversationKey, &dto.LocalIP, &dto.RemoteIP,
		&dto.PrimaryProtocol, &dto.PrimaryLocalPort, &dto.PrimaryRemotePort, &dto.LocalToRemoteBytes, &dto.RemoteToLocalBytes,
		&dto.FlowRecordCount, &dto.ActiveBucketCount, &dto.MaxDurationMS, &dto.PacketBytesP50, &dto.RemoteASN, &dto.RemoteCountry,
		&dto.RemotePrefixID, &dto.LocalPrefixID, &dto.CompleteRatio, &dto.Score, &dto.RiskLevel, &dto.Verdict, &dto.SymmetryRatio, &dto.DominanceRatio,
		&dto.ProbeRecommended, &dto.ProbeBlockReason, &dto.DecisionRuleID, &dto.RuleSetVersion, &familyHints, &dto.Evidence,
		&dto.SourceGeneration, &dto.GeneratedAt, &dto.Disposition, &dto.DispositionNote, &dispositionBy, &dispositionAt,
		&dto.ProbeStatus, &probeJobID, &probeResult, &dto.RowVersion, &dto.CreatedAt, &dto.UpdatedAt); err != nil {
		return vpnFindingDTO{}, err
	}
	if len(familyHints) > 0 {
		if err := json.Unmarshal(familyHints, &dto.FamilyHints); err != nil {
			return vpnFindingDTO{}, err
		}
	}
	if len(probeResult) > 0 {
		dto.ProbeResult = json.RawMessage(probeResult)
	}
	dto.DispositionBy = dispositionBy.String
	if dispositionAt.Valid {
		at := dispositionAt.Time.UTC()
		dto.DispositionAt = &at
	}
	dto.ProbeJobID = probeJobID.String
	return dto, nil
}

func (s *Server) registerFlowVPNFindingRoutes(auth *gin.RouterGroup) {
	view := s.requirePermission("flow.vpn.view")
	triage := s.requirePermission("flow.vpn.triage")
	findings := auth.Group("/flow/vpn/findings")
	findings.GET("", view, s.listVPNFindings)
	findings.GET("/facets", view, s.listVPNFindingFacets)
	findings.POST("/exports", view, s.createVPNFindingsExport)
	findings.GET("/:finding_id", view, s.getVPNFinding)
	findings.POST("/:finding_id/actions/disposition", triage, s.dispositionVPNFinding)
}

// createVPNFindingsExport enqueues an async vpn_findings export of the current
// findings selection (window, text search, column filters, sort). It returns the
// operation job; the artifact is served through the shared export lifecycle.
func (s *Server) createVPNFindingsExport(c *gin.Context) {
	if s.flowQuery == nil || s.jobs == nil {
		fail(c, http.StatusServiceUnavailable, "flow_query_unavailable", "flow ClickHouse store is not configured")
		return
	}
	var req struct {
		From           string              `json:"from"`
		To             string              `json:"to"`
		Search         string              `json:"search"`
		ColumnFilters  map[string][]string `json:"column_filters"`
		SortBy         string              `json:"sort_by"`
		SortDirection  string              `json:"sort_direction"`
		Format         string              `json:"format"`
		MaxRows        uint32              `json:"max_rows"`
		IdempotencyKey string              `json:"idempotency_key"`
	}
	decoder := json.NewDecoder(c.Request.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&req); err != nil {
		fail(c, http.StatusBadRequest, "invalid_request", err.Error())
		return
	}
	format := strings.ToLower(strings.TrimSpace(req.Format))
	if format == "" {
		format = "csv"
	}
	if format != "csv" && format != "parquet" {
		fail(c, http.StatusBadRequest, "invalid_request", "format must be csv or parquet")
		return
	}
	fromTime, errFrom := time.Parse(time.RFC3339Nano, strings.TrimSpace(req.From))
	toTime, errTo := time.Parse(time.RFC3339Nano, strings.TrimSpace(req.To))
	if errFrom != nil || errTo != nil || !toTime.After(fromTime) {
		fail(c, http.StatusBadRequest, "invalid_range", "from and to must be RFC3339 with to after from")
		return
	}
	for field := range req.ColumnFilters {
		if _, allow := vpnFindingFacetColumns[field]; !allow {
			fail(c, http.StatusBadRequest, "invalid_filter", "unsupported filter field: "+field)
			return
		}
	}
	if req.SortBy != "" {
		if _, allow := vpnFindingsExportSortColumns[req.SortBy]; !allow {
			fail(c, http.StatusBadRequest, "invalid_sort", "unsupported sort field")
			return
		}
	}
	maxRows := req.MaxRows
	if maxRows == 0 {
		maxRows = maxFlowDetailExportRows
	}
	if maxRows > maxFlowDetailExportRows {
		fail(c, http.StatusBadRequest, "invalid_request", "max_rows must be 1..250000")
		return
	}
	payload := flowExportPayload{
		Kind: flowExportKindVPNFindings, Format: format, MaxRows: maxRows,
		VPNFindings: &vpnFindingsExportSpec{
			From: fromTime.UTC(), To: toTime.UTC(), Search: strings.TrimSpace(req.Search),
			ColumnFilters: req.ColumnFilters, SortBy: req.SortBy, SortDirection: req.SortDirection,
		},
	}
	s.enqueueFlowExport(c, payload, req.IdempotencyKey)
}

// vpnFindingFacetColumns are the columns the filter-builder may facet on and
// filter by. Membership is the SQL-injection guard: a facet/filter field name is
// interpolated into the query only after passing this allowlist.
var vpnFindingFacetColumns = map[string]struct{}{
	"disposition": {}, "verdict": {}, "risk_level": {}, "probe_status": {}, "remote_country": {},
	"primary_protocol": {}, "primary_local_port": {}, "primary_remote_port": {},
	"local_to_remote_bytes": {}, "remote_to_local_bytes": {}, "remote_asn": {},
	"local_ip": {}, "remote_ip": {}, "remote_prefix_id": {},
}

// vpnFindingFilterExpr builds the shared WHERE clause honored by the facets
// endpoint: the window (from/to), the main text search, and the active column
// filters (filter.<field>=value), skipping excludeField so a facet reflects the
// counts it would have if that field's own selection were cleared.
func (s *Server) vpnFindingFilterExpr(c *gin.Context, excludeField, mainTextParam string) ([]string, []any, bool) {
	where := []string{"1=1"}
	var args []any
	if from, to, ok := s.vpnFindingRange(c); !ok {
		return nil, nil, false
	} else if !from.IsZero() {
		where = append(where, "window_end>=?", "window_end<?")
		args = append(args, from, to)
	}
	if text := strings.TrimSpace(c.Query(mainTextParam)); text != "" {
		like := "%" + escapeLike(text) + "%"
		where = append(where, "(id LIKE ? OR local_ip LIKE ? OR remote_ip LIKE ? OR remote_prefix_id LIKE ?)")
		args = append(args, like, like, like, like)
	}
	for raw, values := range c.Request.URL.Query() {
		if !strings.HasPrefix(raw, "filter.") {
			continue
		}
		field := strings.TrimPrefix(raw, "filter.")
		if field == excludeField {
			continue
		}
		if _, ok := vpnFindingFacetColumns[field]; !ok {
			fail(c, http.StatusBadRequest, "invalid_filter", "unsupported filter field: "+field)
			return nil, nil, false
		}
		placeholders := make([]string, 0, len(values))
		for _, value := range values {
			value = strings.TrimSpace(value)
			if value == "" {
				continue
			}
			if field == "remote_country" {
				value = strings.ToUpper(value)
			}
			placeholders = append(placeholders, "?")
			args = append(args, value)
		}
		if len(placeholders) > 0 {
			where = append(where, field+" IN ("+strings.Join(placeholders, ",")+")")
		}
	}
	return where, args, true
}

// listVPNFindingFacets returns bounded value counts for one findings column, over
// the current filter set, for the filter-builder. `search` is the main text query;
// `q` narrows the returned facet values.
func (s *Server) listVPNFindingFacets(c *gin.Context) {
	field := strings.TrimSpace(c.Query("field"))
	if _, ok := vpnFindingFacetColumns[field]; !ok {
		fail(c, http.StatusBadRequest, "invalid_filter", "unsupported facet field")
		return
	}
	where, args, ok := s.vpnFindingFilterExpr(c, field, "search")
	if !ok {
		return
	}
	if facetSearch := strings.TrimSpace(c.Query("q")); facetSearch != "" {
		where = append(where, field+" LIKE ?")
		args = append(args, "%"+escapeLike(facetSearch)+"%")
	}
	limit := 100
	if raw := strings.TrimSpace(c.Query("limit")); raw != "" {
		if value, err := strconv.Atoi(raw); err == nil && value >= 1 && value <= 500 {
			limit = value
		}
	}
	query := "SELECT " + field + " AS value, COUNT(*) AS count FROM flow_vpn_findings WHERE " +
		strings.Join(where, " AND ") + " GROUP BY " + field + " ORDER BY count DESC, value ASC LIMIT ?"
	rows, err := s.db.QueryContext(c.Request.Context(), query, append(args, limit)...)
	if err != nil {
		writeSQLError(c, err)
		return
	}
	defer rows.Close()
	type facet struct {
		Value string `json:"value"`
		Count int    `json:"count"`
	}
	items := make([]facet, 0, limit)
	for rows.Next() {
		var value sql.NullString
		var count int
		if err := rows.Scan(&value, &count); err != nil {
			writeSQLError(c, err)
			return
		}
		items = append(items, facet{Value: value.String, Count: count})
	}
	if err := rows.Err(); err != nil {
		writeSQLError(c, err)
		return
	}
	c.JSON(http.StatusOK, gin.H{"items": items, "total": len(items), "field": field})
}

// listVPNFindings serves the hub wire contract: `q` text search, `from`/`to`
// window, `filter.<field>` column filters, `sort_by`/`sort_direction`, and
// limit/offset. It does not use parseInventoryPage (which speaks sort/order and
// rejects the frontend's params).
func (s *Server) listVPNFindings(c *gin.Context) {
	where, args, ok := s.vpnFindingFilterExpr(c, "", "q")
	if !ok {
		return
	}
	sortBy := strings.TrimSpace(c.DefaultQuery("sort_by", "window_end"))
	if _, allow := vpnFindingsExportSortColumns[sortBy]; !allow {
		fail(c, http.StatusBadRequest, "invalid_sort", "unsupported sort field")
		return
	}
	direction := "DESC"
	if strings.EqualFold(strings.TrimSpace(c.Query("sort_direction")), "asc") {
		direction = "ASC"
	}
	limit := 100
	if raw := strings.TrimSpace(c.Query("limit")); raw != "" {
		value, err := strconv.Atoi(raw)
		if err != nil || value < 1 || value > 500 {
			fail(c, http.StatusBadRequest, "invalid_filter", "limit must be between 1 and 500")
			return
		}
		limit = value
	}
	offset := 0
	if raw := strings.TrimSpace(c.Query("offset")); raw != "" {
		value, err := strconv.Atoi(raw)
		if err != nil || value < 0 {
			fail(c, http.StatusBadRequest, "invalid_filter", "offset must be a non-negative integer")
			return
		}
		offset = value
	}
	clause := " WHERE " + strings.Join(where, " AND ")
	var total int
	if err := s.db.QueryRowContext(c.Request.Context(), "SELECT COUNT(*) FROM flow_vpn_findings"+clause, args...).Scan(&total); err != nil {
		writeSQLError(c, err)
		return
	}
	query := vpnFindingSelect + clause + " ORDER BY " + sortBy + " " + direction + ", id " + direction + " LIMIT ? OFFSET ?"
	queryArgs := append(append([]any{}, args...), limit, offset)
	rows, err := s.db.QueryContext(c.Request.Context(), query, queryArgs...)
	if err != nil {
		writeSQLError(c, err)
		return
	}
	defer rows.Close()
	items := make([]vpnFindingDTO, 0, limit)
	for rows.Next() {
		item, err := scanVPNFinding(rows)
		if err != nil {
			writeSQLError(c, err)
			return
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		writeSQLError(c, err)
		return
	}
	c.JSON(http.StatusOK, gin.H{
		"items": items, "total": total, "limit": limit, "offset": offset,
		"meta": gin.H{"sort": sortBy + ":" + strings.ToLower(direction)},
	})
}

// vpnFindingRange parses the optional from/to window bound (RFC3339), which must
// be supplied together and positive.
func (s *Server) vpnFindingRange(c *gin.Context) (time.Time, time.Time, bool) {
	rawFrom, rawTo := strings.TrimSpace(c.Query("from")), strings.TrimSpace(c.Query("to"))
	if rawFrom == "" && rawTo == "" {
		return time.Time{}, time.Time{}, true
	}
	from, errFrom := time.Parse(time.RFC3339Nano, rawFrom)
	to, errTo := time.Parse(time.RFC3339Nano, rawTo)
	if errFrom != nil || errTo != nil || !to.After(from) {
		fail(c, http.StatusBadRequest, "invalid_filter", "from and to must be RFC3339 with to after from")
		return time.Time{}, time.Time{}, false
	}
	return from.UTC(), to.UTC(), true
}

func (s *Server) readVPNFinding(ctx context.Context, id string) (vpnFindingDTO, error) {
	return scanVPNFinding(s.db.QueryRowContext(ctx, vpnFindingSelect+" WHERE id=?", id))
}

func (s *Server) getVPNFinding(c *gin.Context) {
	item, err := s.readVPNFinding(c.Request.Context(), c.Param("finding_id"))
	if err != nil {
		writeSQLError(c, err)
		return
	}
	c.Header("ETag", etag(item.RowVersion))
	c.JSON(http.StatusOK, item)
}

func (s *Server) dispositionVPNFinding(c *gin.Context) {
	findingID := c.Param("finding_id")
	expected, supplied, err := ifMatch(c)
	if err != nil {
		fail(c, http.StatusBadRequest, "invalid_if_match", "invalid If-Match")
		return
	}
	if !supplied {
		fail(c, http.StatusPreconditionRequired, "if_match_required", "If-Match with the current quoted row_version is required")
		return
	}
	var input struct {
		Disposition string `json:"disposition"`
		Note        string `json:"note"`
	}
	if !addressDecodeStrict(c, &input, 16<<10) {
		return
	}
	input.Disposition = strings.TrimSpace(input.Disposition)
	input.Note = strings.TrimSpace(input.Note)
	if !validVPNDisposition(input.Disposition) || len(input.Note) > maxVPNFindingNoteBytes {
		fail(c, http.StatusBadRequest, "invalid_request", "disposition is invalid or note is too long")
		return
	}
	p := currentPrincipal(c)
	var actor any = p.UserID
	var at any = time.Now().UTC()
	if input.Disposition == vpnDispositionUnreviewed {
		actor, at = nil, nil
	}
	result, err := s.db.ExecContext(c.Request.Context(), `UPDATE flow_vpn_findings
		SET disposition=?, disposition_note=?, disposition_by=?, disposition_at=?, row_version=row_version+1, updated_at=CURRENT_TIMESTAMP(3)
		WHERE id=? AND row_version=?`,
		input.Disposition, input.Note, actor, at, findingID, expected)
	if err != nil {
		writeSQLError(c, err)
		return
	}
	if changed, _ := result.RowsAffected(); changed != 1 {
		// Distinguish a missing finding from a stale row version.
		var exists bool
		if err := s.db.QueryRowContext(c.Request.Context(), "SELECT EXISTS(SELECT 1 FROM flow_vpn_findings WHERE id=?)", findingID).Scan(&exists); err != nil {
			writeSQLError(c, err)
			return
		}
		if !exists {
			writeSQLError(c, sql.ErrNoRows)
			return
		}
		writeSQLError(c, errVersionConflict)
		return
	}
	updated, err := s.readVPNFinding(c.Request.Context(), findingID)
	if err != nil {
		writeSQLError(c, err)
		return
	}
	s.audit(c.Request.Context(), p.UserID, "flow.vpn_finding.disposition", "flow_vpn_finding", findingID)
	c.Header("ETag", etag(updated.RowVersion))
	c.JSON(http.StatusOK, updated)
}

func containsString(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}
