blank_issues_enabled: false
contact_links:
  - name: 💬 Support and questions
    url: https://github.com/cloudcache/watchdog/discussions
    about: Ask and answer questions here.
  - name: ℹ️ View the Common Issues page
    url: https://github.com/cloudcache/watchdog/tree/main/docs
    about: Find information about commonly encountered problems.
