# Docs: https://github.com/cloudcache/watchdog/tree/main/docs

services:
  watchdog:
    image: cloudcache/watchdog:latest
    container_name: watchdog
    restart: unless-stopped
    environment:
      APP_URL: http://localhost:8090
    ports:
      - 8090:8090
    volumes:
      - ./watchdog_data:/watchdog_data
      - ./watchdog_socket:/watchdog_socket
    # healthcheck:
    #   test: ['CMD', '/watchdog', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s

  watchdog-agent:
    image: cloudcache/watchdog-agent:latest
    container_name: watchdog-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./watchdog_agent_data:/var/lib/watchdog-agent
      - ./watchdog_socket:/watchdog_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /watchdog_socket/watchdog.sock
      HUB_URL: http://localhost:8090
      TOKEN: <token>
      KEY: "<key>"
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s
