import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { routePatterns } from "../src/route-manifest.ts"

const frontendRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const outputRoot = join(frontendRoot, "dist")
const sourceDocument = readFileSync(join(outputRoot, "index.html"), "utf8")
const generatedPageRoot = join(outputRoot, "_pages")

if (!sourceDocument.includes('<div id="app"></div>')) {
	throw new Error("Frontend build output is missing the Watchdog application root")
}

rmSync(generatedPageRoot, { recursive: true, force: true })

const nginxLocations: string[] = [
	"# Generated by frontend/scripts/build-mpa.ts. Do not edit.",
	"location = / {",
	'\tadd_header Cache-Control "no-store" always;',
	"\ttry_files /index.html =404;",
	"}",
]

for (const [name, pattern] of Object.entries(routePatterns)) {
	const document = pageDocument(sourceDocument, name)
	if (!pattern.includes(":")) {
		if (pattern === "/") {
			writeDocument("index.html", document)
			continue
		}
		const relativeDocument = `${pattern.slice(1)}/index.html`
		writeDocument(relativeDocument, document)
		nginxLocations.push(...exactLocation(pattern, `/${relativeDocument}`))
		nginxLocations.push(...exactLocation(`${pattern}/`, `/${relativeDocument}`))
		continue
	}

	const relativeDocument = `_pages/${name}.html`
	writeDocument(relativeDocument, document)
	nginxLocations.push(
		`location ~ ${nginxPattern(pattern)} {`,
		'\tadd_header Cache-Control "no-store" always;',
		`\ttry_files /${relativeDocument} =404;`,
		"}"
	)
}

nginxLocations.push("location = /watchdog-mpa-routes.conf { return 404; }", "location ^~ /_pages/ { return 404; }")
writeFileSync(join(outputRoot, "watchdog-mpa-routes.conf"), `${nginxLocations.join("\n")}\n`)

function writeDocument(relativePath: string, document: string) {
	const destination = join(outputRoot, relativePath)
	mkdirSync(dirname(destination), { recursive: true })
	writeFileSync(destination, document)
}

function pageDocument(document: string, routeName: string): string {
	const loadingShell = [
		'<div id="app">',
		'<main class="watchdog-document-loading" role="status" aria-live="polite">',
		'<div class="watchdog-document-loading__mark">WD</div>',
		'<div class="watchdog-document-loading__line"></div>',
		'<div class="watchdog-document-loading__line watchdog-document-loading__line--short"></div>',
		'<span class="watchdog-document-loading__label">Loading Watchdog…</span>',
		'<a class="watchdog-document-loading__recovery" href="">Loading is taking too long. Reload this page.</a>',
		"</main>",
		"</div>",
	].join("")
	const title = routeName === "home" ? "Watchdog" : `${pageTitle(routeName)} · Watchdog`
	return document
		.replace("<html", `<html data-watchdog-page="${escapeAttribute(routeName)}"`)
		.replace("<title>Watchdog</title>", `<title>${escapeHTML(title)}</title>`)
		.replace('<div id="app"></div>', loadingShell)
}

function pageTitle(routeName: string): string {
	if (routeName === "home") return "Watchdog"
	return routeName
		.split("_")
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
		.join(" ")
}

function exactLocation(path: string, documentPath: string): string[] {
	return [
		`location = ${path} {`,
		'\tadd_header Cache-Control "no-store" always;',
		`\ttry_files ${documentPath} =404;`,
		"}",
	]
}

function nginxPattern(routePattern: string): string {
	const segments = routePattern.split("/").slice(1)
	let pattern = "^"
	for (const segment of segments) {
		if (segment.startsWith(":")) {
			pattern += segment.endsWith("?") ? "(?:/[^/]+)?" : "/[^/]+"
		} else {
			pattern += `/${segment.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`
		}
	}
	return `${pattern}/?$`
}

function escapeHTML(value: string): string {
	return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")
}

function escapeAttribute(value: string): string {
	return escapeHTML(value).replaceAll('"', "&quot;")
}
