CREATE TABLE IF NOT EXISTS network_device_sensors (
  id CHAR(26) PRIMARY KEY,
  tenant_id CHAR(26) NOT NULL,
  device_id CHAR(26) NOT NULL,
  port_id CHAR(26) NULL,
  sensor_index BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sensor_class VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  oid VARCHAR(512) NOT NULL DEFAULT '',
  unit VARCHAR(64) NOT NULL DEFAULT '',
  current_value DOUBLE NULL,
  warn_limit DOUBLE NULL,
  crit_limit DOUBLE NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'unknown',
  metadata_json JSON NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_network_device_sensors_index (tenant_id, device_id, sensor_index, sensor_class),
  KEY idx_network_device_sensors_device_class (tenant_id, device_id, sensor_class),
  KEY idx_network_device_sensors_port (tenant_id, port_id),
  CONSTRAINT fk_network_device_sensors_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_network_device_sensors_device FOREIGN KEY (device_id) REFERENCES network_devices(id) ON DELETE CASCADE,
  CONSTRAINT fk_network_device_sensors_port FOREIGN KEY (port_id) REFERENCES network_ports(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
