-- PLAT-04C: immutable address-library imports. Uploaded artifacts are decoded
-- into a staging generation; only address_import_slots is switched when the
-- complete generation is ready, so readers never observe a partial import.
CREATE TABLE IF NOT EXISTS address_imports (
  id CHAR(26) PRIMARY KEY,
  tenant_id CHAR(26) NOT NULL,
  source_slot VARCHAR(16) NOT NULL,
  format VARCHAR(8) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  artifact_ref VARCHAR(512) NOT NULL,
  checksum_sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT UNSIGNED NOT NULL,
  database_type VARCHAR(128) NULL,
  build_epoch BIGINT NULL,
  ip_version TINYINT UNSIGNED NULL,
  language VARCHAR(16) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'quarantined',
  row_count_v4 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  row_count_v6 BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by CHAR(26) NOT NULL,
  error_code VARCHAR(64) NULL,
  error_detail TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  ready_at DATETIME(3) NULL,
  activated_at DATETIME(3) NULL,
  KEY idx_address_imports_tenant_status (tenant_id, status, created_at),
  KEY idx_address_imports_checksum (tenant_id, checksum_sha256),
  CONSTRAINT fk_address_imports_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_address_imports_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CHECK (source_slot IN ('geo','asn','combined')),
  CHECK (format IN ('mmdb','ipdb')),
  CHECK (status IN ('quarantined','queued','importing','ready','failed','retired')),
  CHECK (ip_version IS NULL OR ip_version IN (4,6))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS address_base_prefixes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id CHAR(26) NOT NULL,
  import_id CHAR(26) NOT NULL,
  family TINYINT UNSIGNED NOT NULL,
  prefix_length TINYINT UNSIGNED NOT NULL,
  cidr VARCHAR(43) NOT NULL,
  ip_start BINARY(16) NOT NULL,
  ip_end BINARY(16) NOT NULL,
  continent_code VARCHAR(16) NULL,
  country_code CHAR(2) NULL,
  country_name VARCHAR(128) NULL,
  subdivision_code VARCHAR(16) NULL,
  subdivision_name VARCHAR(128) NULL,
  city_code VARCHAR(32) NULL,
  city_name VARCHAR(128) NULL,
  asn BIGINT UNSIGNED NULL,
  operator_name VARCHAR(190) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  labels JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_address_base_import_cidr (import_id, cidr),
  KEY idx_address_base_lookup (tenant_id, import_id, family, ip_start),
  KEY idx_address_base_country (tenant_id, import_id, country_code, family, ip_start),
  KEY idx_address_base_asn (tenant_id, import_id, asn, family, ip_start),
  CONSTRAINT fk_address_base_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_address_base_import FOREIGN KEY (import_id) REFERENCES address_imports(id) ON DELETE CASCADE,
  CHECK (family IN (4,6)),
  CHECK ((family = 4 AND prefix_length <= 32) OR (family = 6 AND prefix_length <= 128)),
  CHECK (ip_start <= ip_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS address_import_slots (
  tenant_id CHAR(26) NOT NULL,
  source_slot VARCHAR(16) NOT NULL,
  import_id CHAR(26) NOT NULL,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  activated_by CHAR(26) NOT NULL,
  activated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (tenant_id, source_slot),
  KEY fk_address_import_slots_import (import_id),
  CONSTRAINT fk_address_import_slots_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_address_import_slots_import FOREIGN KEY (import_id) REFERENCES address_imports(id),
  CONSTRAINT fk_address_import_slots_actor FOREIGN KEY (activated_by) REFERENCES users(id),
  CHECK (source_slot IN ('geo','asn','combined'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
