-- FLOW-07C management boundary: editable VPN rule sources and durable scored
-- findings live in MySQL. ClickHouse remains the candidate fact source;
-- operation_jobs remains the only scheduler/probe state machine.
CREATE TABLE IF NOT EXISTS flow_vpn_rules (
  id CHAR(26) NOT NULL,
  tenant_id CHAR(26) NOT NULL,
  name VARCHAR(190) NOT NULL,
  kind VARCHAR(32) NOT NULL DEFAULT 'passive',
  rule_schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  match_json JSON NOT NULL,
  effect VARCHAR(16) NOT NULL,
  weight SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  priority INT NOT NULL DEFAULT 0,
  behavior_json JSON NOT NULL,
  intelligence_json JSON NOT NULL,
  probe_policy_json JSON NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by CHAR(26) NOT NULL,
  updated_by CHAR(26) NOT NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_vpn_rules_tenant_id (tenant_id, id),
  UNIQUE KEY uq_flow_vpn_rules_name (tenant_id, name),
  KEY idx_flow_vpn_rules_list (tenant_id, status, kind, priority, id),
  CONSTRAINT fk_flow_vpn_rules_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CHECK (kind IN ('passive', 'intelligence', 'probe')),
  CHECK (rule_schema_version = 1),
  CHECK (effect IN ('score', 'allow', 'suppress')),
  CHECK (weight <= 100),
  CHECK (status IN ('draft', 'active', 'suspended', 'retired', 'deleted')),
  CHECK (JSON_TYPE(match_json) = 'OBJECT'),
  CHECK (JSON_TYPE(behavior_json) = 'OBJECT'),
  CHECK (JSON_TYPE(intelligence_json) = 'OBJECT'),
  CHECK (JSON_TYPE(probe_policy_json) = 'OBJECT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flow_vpn_findings (
  id CHAR(26) NOT NULL,
  tenant_id CHAR(26) NOT NULL,
  window_start DATETIME(3) NOT NULL,
  window_end DATETIME(3) NOT NULL,
  conversation_key BINARY(32) NOT NULL,
  local_ip VARBINARY(16) NOT NULL,
  remote_ip VARBINARY(16) NOT NULL,
  primary_protocol TINYINT UNSIGNED NOT NULL,
  primary_local_port SMALLINT UNSIGNED NOT NULL,
  primary_remote_port SMALLINT UNSIGNED NOT NULL,
  local_to_remote_bytes BIGINT UNSIGNED NOT NULL,
  remote_to_local_bytes BIGINT UNSIGNED NOT NULL,
  flow_record_count BIGINT UNSIGNED NOT NULL,
  active_bucket_count INT UNSIGNED NOT NULL,
  max_duration_ms BIGINT UNSIGNED NOT NULL,
  remote_asn INT UNSIGNED NOT NULL DEFAULT 0,
  remote_country CHAR(2) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  remote_prefix_id VARCHAR(128) NOT NULL DEFAULT '',
  complete_ratio DECIMAL(9,8) NOT NULL,
  score SMALLINT UNSIGNED NOT NULL,
  risk_level VARCHAR(16) NOT NULL,
  verdict VARCHAR(32) NOT NULL,
  probe_recommended TINYINT(1) NOT NULL DEFAULT 0,
  probe_block_reason VARCHAR(64) NOT NULL DEFAULT '',
  decision_rule_id VARCHAR(128) NOT NULL DEFAULT '',
  evidence_schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  evidence_json JSON NOT NULL,
  rule_set_version VARCHAR(128) NOT NULL,
  dimension_snapshot_id VARCHAR(128) NOT NULL,
  geo_version VARCHAR(128) NOT NULL,
  classification_version BIGINT UNSIGNED NOT NULL,
  source_generation BIGINT UNSIGNED NOT NULL,
  generated_at DATETIME(3) NOT NULL,
  disposition VARCHAR(32) NOT NULL DEFAULT 'unreviewed',
  disposition_note VARCHAR(2000) NOT NULL DEFAULT '',
  disposition_by CHAR(26) NULL,
  disposition_at DATETIME(3) NULL,
  probe_status VARCHAR(32) NOT NULL DEFAULT 'not_requested',
  probe_job_id CHAR(26) NULL,
  probe_result_json JSON NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_flow_vpn_findings_identity
    (tenant_id, window_start, window_end, conversation_key, rule_set_version),
  KEY idx_flow_vpn_findings_list
    (tenant_id, window_end, id),
  KEY idx_flow_vpn_findings_risk
    (tenant_id, risk_level, verdict, window_end, id),
  KEY idx_flow_vpn_findings_triage
    (tenant_id, disposition, probe_status, window_end, id),
  KEY idx_flow_vpn_findings_expiry (expires_at, tenant_id, id),
  KEY idx_flow_vpn_findings_probe_job (probe_job_id),
  KEY idx_flow_vpn_findings_disposition_by (disposition_by),
  CONSTRAINT fk_flow_vpn_findings_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CHECK (window_end > window_start),
  CHECK (OCTET_LENGTH(local_ip) = 16),
  CHECK (OCTET_LENGTH(remote_ip) = 16),
  CHECK (primary_protocol > 0),
  CHECK (flow_record_count > 0),
  CHECK (active_bucket_count > 0),
  CHECK (complete_ratio BETWEEN 0 AND 1),
  CHECK (score <= 100),
  CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
  CHECK (verdict IN ('observe', 'review', 'probe_candidate', 'allowlisted', 'suppressed')),
  CHECK (evidence_schema_version = 1),
  CHECK (JSON_TYPE(evidence_json) = 'OBJECT'),
  CHECK (disposition IN ('unreviewed', 'confirmed', 'false_positive', 'allowed', 'suppressed')),
  CHECK (probe_status IN ('not_requested', 'queued', 'running', 'completed', 'failed', 'canceled')),
  CHECK (JSON_TYPE(probe_result_json) = 'OBJECT'),
  CHECK ((disposition = 'unreviewed' AND disposition_by IS NULL AND disposition_at IS NULL)
      OR (disposition <> 'unreviewed' AND disposition_by IS NOT NULL AND disposition_at IS NOT NULL)),
  CHECK ((probe_status = 'not_requested' AND probe_job_id IS NULL)
      OR (probe_status <> 'not_requested' AND probe_job_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
