# Specialized images available for Nvidia / Intel GPUs
#
# Docs: https://github.com/cloudcache/watchdog/tree/main/docs

services:
  watchdog-agent:
    image: cloudcache/watchdog-agent
    container_name: watchdog-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./watchdog_agent_data:/var/lib/watchdog-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.watchdog:/extra-filesystems/disk1:ro
    environment:
      LISTEN: 45876
      KEY: "<public key>"
      HUB_URL: "<hub url>"
      TOKEN: "<token>"
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s
