# Docs: https://github.com/cloudcache/watchdog/tree/main/docs

services:
  watchdog:
    image: "cloudcache/watchdog"
    container_name: "watchdog"
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./watchdog_data:/watchdog_data
    # healthcheck:
    #   test: ['CMD', '/watchdog', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s
